import type { Incident } from "./types";
import { distributeCorrectAnswer } from "./answer-options";
import { webInfrastructureIncidents } from "./web-incidents";

type IncidentInput = Omit<Incident, "status" | "level" | "deploymentDetails" | "environmentDetails" | "timeline" | "notes" | "customerContext" | "businessImpact"> &
  Partial<Pick<Incident, "deploymentDetails" | "environmentDetails" | "timeline" | "notes" | "customerContext" | "businessImpact">>;

const build = (incident: IncidentInput): Incident => distributeCorrectAnswer({
  status: "Open",
  level: incident.difficulty,
  deploymentDetails: "Runtime: Node.js 20\nRegion: iad\nRelease: v42\nDeployment status: successful",
  environmentDetails: "NODE_ENV=production\nPORT=8080\nSecrets are redacted in support views.",
  customerContext: {
    customer: "Northstar AI",
    plan: incident.severity === "Critical" ? "Enterprise" : "Scale",
    environment: "Production",
    affectedUsers: incident.severity === "Critical" ? "All users" : "Multiple customer workspaces",
    region: "US-East",
    started: "42 minutes ago",
  },
  businessImpact: {
    serviceImpact: incident.customerImpact,
    estimatedAffectedUsers: incident.severity === "Critical" ? "4,800 active users" : incident.severity === "High" ? "1,200 active users" : "Approximately 180 users",
    businessImpact: incident.severity === "Critical" ? "Customer-facing production workflow unavailable" : "Production workflow degraded; support volume increasing",
    priority: incident.severity === "Critical" ? "P1 — Critical" : incident.severity === "High" ? "P2 — High" : "P3 — Standard",
    revenueImpact: incident.severity === "Critical" || incident.severity === "High" ? "Paid production usage and SLA commitments at risk" : "No direct revenue loss confirmed",
  },
  timeline: [
    { time: "09:42 UTC", event: "Customer reports issue" },
    { time: "09:44 UTC", event: "Support reproduces the reported failure" },
    { time: "09:47 UTC", event: "Application logs correlated by request ID" },
    { time: "09:50 UTC", event: "API and deployment evidence compared" },
    { time: "09:54 UTC", event: "Root cause identified" },
    { time: "09:57 UTC", event: "Resolution validated and service restored" },
  ],
  notes: "Confirm the request ID, isolate whether the failure is client-side or provider-side, and avoid asking the customer to share secret values.",
  ...incident,
  customerMessage: incident.customerMessage.startsWith("Hi ") ? incident.customerMessage : `Hi Support,\n\n${incident.customerMessage}\n\nCould you help us investigate? We can provide request IDs or sanitized examples if needed.`,
});

export const incidents: Incident[] = [
  build({
    id: "missing-elevenlabs-key", incidentId: "INC-0001", title: "Voice requests fail after production deploy", product: "ElevenLabs", severity: "High", category: "Authentication", difficulty: "Foundational", error: "401 Unauthorized",
    customerMessage: "Text-to-speech works locally, but every production request fails immediately after our Fly.io deployment.",
    customerImpact: "All production voice generation is unavailable; the staging environment is unaffected.",
    logs: `[2026-07-05T09:42:18.441Z] POST /api/voice 401 43ms\n[voice] provider=elevenlabs request_id=req_7d8f2\n[voice] auth_header_present=false\n[voice] provider authentication failed status=401`,
    apiRequest: `POST /v1/text-to-speech/21m00Tcm4TlvDq8ikWAM\nContent-Type: application/json\nxi-api-key: [not set]\n\n{ "text": "Your order is ready.", "model_id": "eleven_multilingual_v2" }`,
    apiResponse: `{\n  "status": 401,\n  "detail": { "status": "missing_api_key", "message": "A valid API key is required" },\n  "request_id": "req_7d8f2"\n}`,
    deploymentDetails: `fly deploy: successful\nMachine: 148ed26a\nInternal port: 8080\nRelease: v42\n\n$ fly secrets list\nNAME                 DIGEST\nOPENAI_API_KEY       7d93****\n# ELEVENLABS_API_KEY is absent`,
    environmentDetails: `Local: ELEVENLABS_API_KEY=[configured]\nProduction: ELEVENLABS_API_KEY=[missing]\nNODE_ENV=production\nPORT=8080`,
    choices: ["The selected voice was deleted", "ELEVENLABS_API_KEY is missing from Fly.io secrets", "The app is listening on the wrong port", "The account character quota is exhausted"], correctAnswer: 1,
    explanation: "The provider rejects the request before generation because no API credential is sent. Local success plus the missing Fly.io secret isolates the problem to production configuration.",
    investigationSummary: { rootCause: "ELEVENLABS_API_KEY was not configured as a Fly.io secret.", evidence: ["auth_header_present=false in application logs", "Fly.io secret inventory does not include ELEVENLABS_API_KEY", "The same request succeeds in the configured local environment"], impact: "Every production text-to-speech request returned 401, blocking voice output.", resolution: "Set the secret with fly secrets set ELEVENLABS_API_KEY=… and verify the restarted Machine with a diagnostic request." },
    prevention: "Validate required environment variables at startup and add a deployment smoke test that checks provider authentication without exposing keys.",
    customerFriendlyReply: "We found that the production service was not receiving its voice API credential after deployment. We have added the missing configuration and confirmed authentication is working. No customer data was affected.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "invalid-elevenlabs-key", incidentId: "INC-0002", title: "Authentication rejected with configured key", product: "ElevenLabs", severity: "High", category: "Authentication", difficulty: "Foundational", error: "401 Unauthorized",
    customerMessage: "The API key is definitely present, but our requests started returning unauthorized this morning.", customerImpact: "Voice generation is blocked in the production workspace.",
    logs: `[10:11:04.008] provider request failed status=401 request_id=req_f13a9\n[10:11:04.009] env ELEVENLABS_API_KEY present=true length=32\n[10:11:04.009] error=invalid_api_key`,
    apiRequest: `GET /v1/user\nxi-api-key: [REDACTED]`, apiResponse: `{ "status": 401, "detail": { "status": "invalid_api_key", "message": "Invalid API key" } }`,
    environmentDetails: `ELEVENLABS_API_KEY=[configured, 32 chars]\nKEY_SOURCE=staging-password-manager\nAPP_ENV=production`,
    choices: ["The API key is incorrect, expired, or from the wrong environment", "The audio MIME type is wrong", "The request exceeded its timeout", "The Fly.io health check path is missing"], correctAnswer: 0,
    explanation: "The key exists and is being sent, but the provider explicitly identifies it as invalid. The source label also points to a staging/production mix-up.",
    investigationSummary: { rootCause: "The configured API key is incorrect, expired, or copied from the wrong environment.", evidence: ["Credential is present and sent", "Provider returns invalid_api_key", "Production configuration references the staging password manager"], impact: "Authenticated ElevenLabs operations fail with 401.", resolution: "Create or retrieve the correct production key, rotate the deployed secret, and revoke the invalid credential." },
    prevention: "Label credentials by environment, document rotation ownership, and run a safe credential check after secret changes.", customerFriendlyReply: "The credential used by the production service was no longer valid for this workspace. We rotated it securely and confirmed that voice requests are succeeding again.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "voice-id-not-found", incidentId: "INC-0003", title: "Saved voice returns not found", product: "ElevenLabs", severity: "Medium", category: "Voice Generation", difficulty: "Foundational", error: "404 Not Found",
    customerMessage: "One saved narrator voice stopped working, while the default voices still generate audio.", customerImpact: "A single production narration workflow cannot generate new clips.",
    logs: `[11:08:31] POST text-to-speech voice_id=pNInz6obpgDQGcFmaJgX-old\n[11:08:31] response=404 status=voice_not_found request_id=req_2bc41`,
    apiRequest: `POST /v1/text-to-speech/pNInz6obpgDQGcFmaJgX-old\n{ "text": "Chapter one", "model_id": "eleven_multilingual_v2" }`, apiResponse: `{ "status": 404, "detail": { "status": "voice_not_found", "message": "Voice does not exist or is not accessible" } }`,
    choices: ["The voice ID does not exist or is unavailable to this account", "The API key is missing", "The browser blocked the response with CORS", "The account is rate limited"], correctAnswer: 0,
    explanation: "Authentication succeeds and other voices work. The failure follows one voice identifier, which is absent from the account's accessible voice list.",
    investigationSummary: { rootCause: "The requested voice ID does not exist or is not available to the account.", evidence: ["Only one voice ID fails", "Provider returns voice_not_found", "The ID is absent from the account voice list"], impact: "Jobs tied to the stale voice configuration fail.", resolution: "Select an accessible voice, update the stored voice ID, and retry the failed jobs." },
    prevention: "Validate saved voice IDs against the provider voice list and handle removed voices with a clear fallback state.", customerFriendlyReply: "The affected workflow referenced a voice that is no longer available to this account. We updated the configuration to an accessible voice and restored generation.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "model-unavailable", incidentId: "INC-0004", title: "Voice and model combination rejected", product: "ElevenLabs", severity: "Medium", category: "Voice Generation", difficulty: "Operational", error: "400 Bad Request",
    customerMessage: "Our new low-latency model works for stock voices but fails for a legacy cloned voice.", customerImpact: "Real-time generation for the legacy voice is unavailable.",
    logs: `[12:03:11] voice_id=legacy_73 model_id=eleven_flash_v2_5\n[12:03:11] 400 model_not_supported request_id=req_b8810`,
    apiRequest: `POST /v1/text-to-speech/legacy_73\n{ "text": "System ready", "model_id": "eleven_flash_v2_5" }`, apiResponse: `{ "status": 400, "detail": { "status": "model_not_supported", "message": "Model is not available for this voice" } }`,
    choices: ["The selected model is unsupported for this voice or endpoint", "The Fly Machine ran out of memory", "The key belongs to another account", "The response was parsed as JSON"], correctAnswer: 0,
    explanation: "The provider accepts the request and identifies the incompatible model/voice pairing. A supported model works with the same credential and voice.",
    investigationSummary: { rootCause: "The selected model is not supported for the requested voice or endpoint.", evidence: ["model_not_supported response", "Stock voices work with the new model", "Legacy voice succeeds with the prior model"], impact: "Requests using the incompatible pairing fail before synthesis.", resolution: "Use a model supported by the voice or migrate the voice through the appropriate provider workflow." },
    prevention: "Load supported models dynamically and validate compatibility before sending generation requests.", customerFriendlyReply: "The selected generation model is not compatible with this legacy voice. We switched the workflow to a supported model and confirmed audio generation is restored.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "rate-limit", incidentId: "INC-0005", title: "Traffic burst triggers provider throttling", product: "ElevenLabs", severity: "High", category: "Rate Limit", difficulty: "Operational", error: "429 Too Many Requests",
    customerMessage: "Batch generation starts normally, then most jobs fail within a few seconds.", customerImpact: "Large content batches complete only partially and require manual retry.",
    logs: `[13:14:00] batch=job_582 concurrency=40\n[13:14:02] 429 rate_limit_exceeded retry_after=2 request_id=req_51de0\n[13:14:02] immediate_retry=true attempt=2\n[13:14:02] 429 rate_limit_exceeded`,
    apiRequest: `POST /v1/text-to-speech/voice_21\nX-Client-Concurrency: 40\n{ "text": "..." }`, apiResponse: `{ "status": 429, "detail": { "status": "rate_limit_exceeded" }, "retry_after": 2 }`,
    choices: ["Too many requests were sent in a short time", "The voice ID was deleted", "The account API key is missing", "The app uses the wrong port"], correctAnswer: 0,
    explanation: "The synchronized burst and explicit 429 response show provider throttling. Immediate retries amplify the traffic instead of allowing recovery.",
    investigationSummary: { rootCause: "Too many generation requests were sent in a short time.", evidence: ["Concurrency jumps to 40", "Provider responds 429 with retry_after", "Immediate retries receive the same response"], impact: "Batch jobs are throttled and partially fail.", resolution: "Honor Retry-After, add exponential backoff with jitter, cap concurrency, and smooth request bursts through a queue." },
    prevention: "Use bounded concurrency, retry budgets, queue visibility, and metrics for 429 rates.", customerFriendlyReply: "A burst of simultaneous generation requests exceeded the provider's short-term request limit. We have slowed and queued the workload, and retries now wait before resubmitting.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "quota-reached", incidentId: "INC-0006", title: "Character allowance exhausted", product: "ElevenLabs", severity: "High", category: "Billing/Quota", difficulty: "Foundational", error: "402 Payment Required",
    customerMessage: "Every voice fails now, even very short text. It worked until our overnight content run.", customerImpact: "No new audio can be generated until usage capacity is restored.",
    logs: `[02:00:01] nightly_job characters_submitted=118420\n[06:20:14] provider status=402 code=quota_exceeded\n[06:20:14] character_count=42 request_id=req_8ab02`,
    apiRequest: `POST /v1/text-to-speech/voice_21\n{ "text": "Your verification code is 4832." }`, apiResponse: `{ "status": 402, "detail": { "status": "quota_exceeded", "message": "Character limit reached" } }`,
    choices: ["The plan quota or character usage limit has been reached", "The selected voice is private", "The audio response has no codec", "DNS resolution failed"], correctAnswer: 0,
    explanation: "All voices and even short inputs fail after a high-volume run, while the provider explicitly reports quota exhaustion.",
    investigationSummary: { rootCause: "The account reached its plan quota or character usage limit.", evidence: ["quota_exceeded response", "Large overnight character usage", "Failure affects all voices and request sizes"], impact: "The provider blocks all new synthesis for the account.", resolution: "Review usage, add capacity or wait for renewal, then retry only eligible failed jobs." },
    prevention: "Alert before quota thresholds, expose usage to operators, and cap non-critical batch workloads.", customerFriendlyReply: "The account reached its current character allowance during the overnight batch. We identified the usage source and are restoring capacity; existing audio remains unaffected.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "generation-timeout", incidentId: "INC-0007", title: "Long-form generation exceeds gateway timeout", product: "ElevenLabs", severity: "Medium", category: "Latency", difficulty: "Escalation", error: "Request timeout",
    customerMessage: "Short previews work, but generating full training scripts fails after exactly 30 seconds.", customerImpact: "Long-form audio jobs fail; short interactive requests continue normally.",
    logs: `[14:21:00] synthesis start chars=18422 timeout_ms=30000\n[14:21:30] upstream timeout elapsed_ms=30001\n[14:21:31] provider completion observed after client disconnect`,
    apiRequest: `POST /api/voice/generate\nX-Request-Timeout: 30000\n{ "text_length": 18422, "stream": false }`, apiResponse: `{ "status": 504, "error": "UPSTREAM_TIMEOUT", "elapsed_ms": 30001 }`,
    choices: ["Generation exceeded the configured request timeout", "The API key has expired", "The webhook secret is stale", "The model name is misspelled"], correctAnswer: 0,
    explanation: "Failures occur at the exact gateway timeout and correlate with request length. Provider completion after disconnect rules out a hard provider rejection.",
    investigationSummary: { rootCause: "The generation request took longer than the configured 30-second timeout.", evidence: ["Failure consistently at 30 seconds", "Only long requests fail", "Provider completes after the client disconnects"], impact: "Long-form jobs are reported failed and may waste completed provider work.", resolution: "Reduce or chunk request length, tune timeouts for the workload, add safe retries/idempotency, and check provider status for unusual latency." },
    prevention: "Move long work to asynchronous jobs, track duration percentiles, and use idempotency keys.", customerFriendlyReply: "Long scripts were taking longer than our gateway allowed, so the connection closed before generation completed. We are processing these jobs in smaller, trackable segments and have adjusted the timeout safely.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "audio-playback", incidentId: "INC-0008", title: "Generated audio cannot play in browser", product: "ElevenLabs", severity: "Medium", category: "Audio Output", difficulty: "Operational", error: "Audio decode error",
    customerMessage: "The request returns 200, but the player shows 0:00 and the console says the audio source is unsupported.", customerImpact: "Audio is generated and billed but cannot be played by end users.",
    logs: `[15:02:44] upstream status=200 content-type=audio/mpeg bytes=48291\n[15:02:44] frontend response.json()\n[15:02:44] SyntaxError: Unexpected token 'I', "ID3..." is not valid JSON`,
    apiRequest: `POST /v1/text-to-speech/voice_21\nAccept: audio/mpeg\n{ "text": "Welcome back" }`, apiResponse: `HTTP/1.1 200 OK\nContent-Type: audio/mpeg\nContent-Length: 48291\n\n[ID3 BINARY AUDIO DATA]`,
    choices: ["The frontend treats binary audio as JSON or uses the wrong content type", "The voice is unavailable", "The plan quota is exhausted", "The request lacks an API key"], correctAnswer: 0,
    explanation: "The provider returns valid MPEG bytes, but the frontend calls response.json(). The client must create a Blob/object URL using the audio content type.",
    investigationSummary: { rootCause: "The frontend is treating binary audio as JSON instead of audio/mpeg.", evidence: ["200 response with Content-Type: audio/mpeg", "Response begins with an ID3 header", "response.json() throws before playback"], impact: "Successfully generated audio cannot be consumed in the browser.", resolution: "Read the response as a Blob/ArrayBuffer, preserve audio/mpeg, create an object URL, and revoke it after playback." },
    prevention: "Add response-content-type tests and a browser playback smoke test.", customerFriendlyReply: "Audio generation was working, but our browser code interpreted the returned audio bytes as text data. We corrected the response handling and confirmed playback across supported browsers.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "webhook-signature", incidentId: "INC-0009", title: "Signed webhooks rejected after secret rotation", product: "ElevenLabs-style Webhook", severity: "High", category: "Webhook", difficulty: "Escalation", error: "Invalid signature",
    customerMessage: "Webhook deliveries show 401 after we rotated secrets. Manual POSTs still reach the endpoint.", customerImpact: "Completion events are not processed, leaving jobs stuck in a processing state.",
    logs: `[16:10:09] POST /webhooks/voice 401\n[webhook] signature_header=true timestamp_valid=true\n[webhook] computed_signature=98ac… received_signature=22f1…\n[webhook] error=signature_mismatch`,
    apiRequest: `POST /webhooks/voice\neleven-signature: t=1783248609,v1=22f1…\nContent-Type: application/json\n\n{ "type": "generation.complete", "id": "gen_883" }`, apiResponse: `{ "status": 401, "error": "invalid_signature" }`,
    environmentDetails: `Provider signing secret version: whsec_v4\nFly.io WEBHOOK_SECRET version: whsec_v3\nRaw request body available: true`,
    choices: ["The webhook secret differs between provider and app environment", "The event timestamp is too old", "The endpoint returns the wrong audio type", "The Fly app is on the wrong port"], correctAnswer: 0,
    explanation: "The header and raw body are available, but signatures differ immediately after rotation. Version evidence confirms the app retains the old secret.",
    investigationSummary: { rootCause: "The webhook secret does not match between the provider and deployed application.", evidence: ["Computed and received signatures differ", "Timestamps validate", "Provider uses v4 while Fly.io still has v3"], impact: "Valid provider events are rejected, so downstream job state is stale.", resolution: "Update the deployed webhook secret, restart safely, replay failed events, and verify signature checks using the raw body." },
    prevention: "Use an overlap window during rotations and monitor webhook rejection rates.", customerFriendlyReply: "A signing-secret rotation left the receiving service on the previous version, so valid events were rejected. We synchronized the secure configuration and replayed the missed events.",
  }),
  build({
    id: "agent-webhook-500", incidentId: "INC-0010", title: "Conversational agent tool call returns 500", product: "ElevenLabs-style Conversational AI", severity: "Critical", category: "Webhook/API", difficulty: "Escalation", error: "500 Internal Server Error",
    customerMessage: "The agent speaks normally, but hangs whenever it tries to look up an order.", customerImpact: "All conversations requiring external order data fail at the tool-call step.",
    logs: `[17:31:52] POST /api/tools/order-status\n[17:31:52] Error: ORDER_SERVICE_URL is not defined\n    at lookupOrder (order-service.ts:18)\n[17:31:52] response=500 duration=12ms`,
    apiRequest: `POST /api/tools/order-status\n{ "order_id": "ORD-10482" }`, apiResponse: `{ "status": 500, "request_id": "tool_7fa1", "error": "INTERNAL_SERVER_ERROR" }`,
    deploymentDetails: `Release: v48 (successful)\nHealth check: passing\nEndpoint: publicly reachable\nSecret inventory: ORDER_SERVICE_TOKEN present\nEnvironment: ORDER_SERVICE_URL absent`,
    environmentDetails: `ORDER_SERVICE_TOKEN=[configured]\nORDER_SERVICE_URL=[missing]\nNODE_ENV=production`,
    choices: ["The webhook endpoint crashes because a required environment variable is missing", "The voice model is unavailable", "The agent exceeded character quota", "The browser blocked a CORS preflight"], correctAnswer: 0,
    explanation: "The conversational layer works until the external tool executes. The fast 500 and stack trace isolate the failure to missing backend configuration.",
    investigationSummary: { rootCause: "The webhook endpoint returns 500 because ORDER_SERVICE_URL is missing.", evidence: ["Stack trace names the missing variable", "Health and reachability checks pass", "Only external-data tool calls fail"], impact: "Agents cannot complete conversations that require order lookup.", resolution: "Configure ORDER_SERVICE_URL, validate connectivity, deploy, and replay a representative tool call." },
    prevention: "Fail fast on required configuration at startup and include tool endpoints in deployment smoke tests.", customerFriendlyReply: "The agent's order lookup service was missing a required production endpoint setting. We restored the configuration and verified that order lookups complete successfully again.",
  }),
  build({
    id: "openai-invalid-key", incidentId: "INC-0011", title: "Incident summarizer loses OpenAI access", product: "OpenAI", severity: "Medium", category: "Authentication", difficulty: "Foundational", error: "401 Unauthorized",
    customerMessage: "Voice still works, but the AI-generated incident summaries now fail for every ticket.", customerImpact: "Agents must write summaries manually; core voice workflows are unaffected.",
    logs: `[18:04:09] summary provider=openai status=401 request_id=req_oa_812\n[18:04:09] code=invalid_api_key OPENAI_API_KEY present=true`,
    apiRequest: `POST /v1/responses\nAuthorization: Bearer [REDACTED]\n{ "model": "gpt-4.1-mini", "input": "Summarize incident..." }`, apiResponse: `{ "error": { "message": "Incorrect API key provided", "type": "invalid_request_error", "code": "invalid_api_key" } }`,
    choices: ["OPENAI_API_KEY is invalid or missing", "ElevenLabs is rate limiting voice", "The Fly app port is wrong", "The webhook signature is stale"], correctAnswer: 0,
    explanation: "The OpenAI endpoint explicitly rejects authentication while unrelated voice operations remain healthy.",
    investigationSummary: { rootCause: "OPENAI_API_KEY is invalid or missing for the summarization service.", evidence: ["OpenAI returns invalid_api_key", "All summary requests fail", "Voice workflows remain healthy"], impact: "Automated incident summaries are unavailable.", resolution: "Rotate or configure the OpenAI key securely and run the minimal diagnostic before restoring traffic." },
    prevention: "Use secret-expiry ownership, safe post-deploy diagnostics, and graceful manual fallbacks.", customerFriendlyReply: "The credential used by our incident-summary service was invalid. We replaced it securely and verified summary generation; voice services were not affected.", diagnosticProvider: "openai",
  }),
  build({
    id: "fly-wrong-port", incidentId: "INC-0012", title: "Healthy build returns 502 at edge", product: "Fly.io", severity: "Critical", category: "Deployment", difficulty: "Operational", error: "502 Bad Gateway",
    customerMessage: "The deploy is green and the Machine is running, but the public URL only returns 502.", customerImpact: "The entire production support console is unreachable.",
    logs: `2026-07-05T18:33:01Z app[148ed26a] [info] Ready on http://0.0.0.0:3000\n2026-07-05T18:33:05Z proxy[148ed26a] [error] connect failed: tcp 172.19.2.4:8080: connection refused`,
    apiRequest: `GET https://support-lab.fly.dev/healthz`, apiResponse: `HTTP/2 502\nfly-error: connection refused`,
    deploymentDetails: `[http_service]\n  internal_port = 8080\n\nApplication log:\n  listening on 0.0.0.0:3000`,
    choices: ["The app is not listening on Fly.io's expected internal port", "The OpenAI key is invalid", "The voice ID is unavailable", "The browser parsed audio as JSON"], correctAnswer: 0,
    explanation: "The Fly Proxy connects to port 8080 while the process listens on 3000. A successful build does not guarantee runtime network alignment.",
    investigationSummary: { rootCause: "The app is not listening on the expected Fly.io internal port.", evidence: ["Proxy connection refused on 8080", "Application reports listening on 3000", "fly.toml routes to internal_port 8080"], impact: "All external requests return 502.", resolution: "Set PORT=8080 (and HOSTNAME=0.0.0.0), redeploy, then verify /healthz through the public edge." },
    prevention: "Keep runtime PORT aligned with fly.toml and test the container using production environment variables.", customerFriendlyReply: "The deployment was running, but it was listening on a different internal port than the edge proxy expected. We aligned the configuration and restored access.",
  }),
  build({
    id: "health-check-failure", incidentId: "INC-0013", title: "Machines repeatedly replaced by health checks", product: "Fly.io", severity: "High", category: "Health Check", difficulty: "Operational", error: "Health check failing",
    customerMessage: "The app briefly comes online after deploy, then Machines restart and traffic becomes intermittent.", customerImpact: "Users see intermittent errors during repeated restarts.",
    logs: `2026-07-05T19:12:11Z health[148ed26a] GET /healthz status=404\n2026-07-05T19:12:26Z health[148ed26a] critical check failed (3 consecutive)\n2026-07-05T19:12:27Z app[148ed26a] Sending signal SIGTERM`,
    apiRequest: `GET /healthz\nUser-Agent: Fly-Health-Check/1.0`, apiResponse: `HTTP/1.1 404 Not Found\nContent-Type: text/html`,
    deploymentDetails: `[[http_service.checks]]\n  path = "/healthz"\n  method = "GET"\n  interval = "15s"\nExpected status: 200`,
    choices: ["The /healthz endpoint does not return 200 OK", "The provider character quota is exhausted", "A CORS header is missing", "The voice model is unsupported"], correctAnswer: 0,
    explanation: "The process starts and serves traffic, but the configured health path returns 404 and triggers replacement.",
    investigationSummary: { rootCause: "The configured /healthz endpoint does not return 200 OK.", evidence: ["Health probe receives 404", "Three failed checks precede SIGTERM", "Process initially starts successfully"], impact: "Healthy processes are repeatedly removed, causing intermittent availability.", resolution: "Implement a lightweight /healthz route returning 200, deploy, and confirm checks remain passing." },
    prevention: "Test the exact health path in CI and keep health checks independent of optional external providers.", customerFriendlyReply: "Our platform health check was pointed at a route the application did not provide, causing healthy instances to restart. We added the endpoint and confirmed stable service.",
  }),
  build({
    id: "cors-blocked", incidentId: "INC-0014", title: "Browser blocks API from new frontend domain", product: "Internal API", severity: "Medium", category: "API", difficulty: "Operational", error: "Browser blocked request",
    customerMessage: "The API works in curl and Postman, but the newly launched web app cannot load any incidents.", customerImpact: "Browser users on the new domain cannot access incident data.",
    logs: `[20:01:33] OPTIONS /api/incidents 204 origin=https://support.example.com\n[20:01:33] cors allowed=false configured_origins=https://app.example.com`,
    apiRequest: `OPTIONS /api/incidents\nOrigin: https://support.example.com\nAccess-Control-Request-Method: GET`, apiResponse: `HTTP/1.1 204 No Content\nAccess-Control-Allow-Origin: https://app.example.com`,
    environmentDetails: `CORS_ALLOWED_ORIGINS=https://app.example.com\nFrontend origin=https://support.example.com\nAPI reachable=true`,
    choices: ["The frontend domain is not allowed in the API CORS configuration", "The Fly Machine is listening on the wrong port", "The API key is expired", "The voice response has an invalid codec"], correctAnswer: 0,
    explanation: "Non-browser clients succeed because they do not enforce CORS. The response allows the old origin rather than the requesting frontend origin.",
    investigationSummary: { rootCause: "The new frontend domain is not included in the API's CORS allowlist.", evidence: ["curl and Postman succeed", "Browser preflight origin differs from allowed origin", "API is reachable and responds 204"], impact: "Browsers block otherwise valid API responses for the new site.", resolution: "Add the exact trusted frontend origin, deploy, and verify preflight and credential settings." },
    prevention: "Manage allowed origins per environment and include browser-origin tests in release checks.", customerFriendlyReply: "The API was healthy, but its browser security allowlist still referenced the previous web address. We added the new trusted domain and confirmed access is restored.",
  }),
  build({
    id: "stream-interrupted", incidentId: "INC-0015", title: "Streaming audio stops mid-response", product: "ElevenLabs", severity: "High", category: "Streaming", difficulty: "Escalation", error: "Stream closed unexpectedly",
    customerMessage: "Our phone assistant begins speaking normally, then audio cuts out between 20 and 25 seconds. Short prompts complete and the same session works in staging. This began after we introduced a new edge proxy configuration this morning.",
    customerImpact: "Long conversational responses terminate early while short utterances remain available.",
    customerContext: { customer: "Beacon Health", plan: "Enterprise", environment: "Production", affectedUsers: "Callers with responses over 20 seconds", region: "EU-West", started: "1 hour ago" },
    businessImpact: { serviceImpact: "Long streaming responses are truncated", estimatedAffectedUsers: "About 640 callers", businessImpact: "Patient scheduling calls require agent handoff", priority: "P2 — High", revenueImpact: "Contact-center SLA at risk" },
    logs: `[10:18:02.104] stream_open request_id=req_94cc1 upstream_status=200\n[10:18:24.110] downstream_close bytes_sent=381204 reason=client_disconnected\n[10:18:24.111] upstream_cancelled elapsed_ms=22007`,
    apiRequest: `POST /v1/text-to-speech/voice_live/stream\nAccept: audio/mpeg\nTransfer-Encoding: chunked\n\n{ "text_length": 1840, "model_id": "eleven_flash_v2_5" }`,
    apiResponse: `HTTP/1.1 200 OK\nContent-Type: audio/mpeg\nTransfer-Encoding: chunked\n\n[valid audio chunks; upstream still producing at 22s]`,
    deploymentDetails: `Release: proxy-v18\nChange: response_timeout 60s -> 22s\nApplication release unchanged\nStaging proxy response_timeout=60s`,
    environmentDetails: `STREAM_IDLE_TIMEOUT_MS=60000\nEDGE_RESPONSE_TIMEOUT_MS=22000\nProvider latency p95=31s`,
    choices: ["The edge proxy closes valid streams at its 22-second response timeout", "The selected voice was deleted", "The request body contains malformed JSON", "The account character quota is exhausted"], correctAnswer: 0,
    explanation: "The upstream returns valid audio and remains active when the downstream closes at a repeatable 22 seconds. Only production has the shortened proxy timeout.",
    investigationSummary: { rootCause: "A production edge-proxy response timeout closed active audio streams after 22 seconds.", evidence: ["Downstream closes at 22 seconds while upstream is still producing", "Short streams succeed", "The proxy release reduced only the production timeout"], impact: "Long audio responses were truncated for production callers.", resolution: "Restore the streaming-safe timeout, exempt active chunked responses from idle handling, and verify a 60-second synthesis through the edge." },
    prevention: "Add long-stream canaries, monitor premature disconnects, validate proxy timeouts in release review, and preserve streaming configuration in infrastructure tests.",
    customerFriendlyReply: "We found that a production network timeout was closing longer audio streams while they were still active. We corrected the timeout and confirmed that extended responses now play through completely.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "webhook-retry-storm", incidentId: "INC-0016", title: "Webhook deliveries repeat after successful processing", product: "ElevenLabs-style Webhook", severity: "High", category: "Webhook", difficulty: "Operational", error: "Repeated delivery",
    customerMessage: "Completed generation events are being applied more than once, creating duplicate records in our CRM. Our endpoint logs show the same event ID several times even though the first request appears to finish successfully.",
    customerImpact: "Duplicate webhook processing creates repeated customer records and manual cleanup.",
    logs: `[11:03:14] event=evt_77b attempt=1 processing=complete elapsed_ms=8421 response_status=504\n[11:03:24] event=evt_77b attempt=2 duplicate=false processing=complete\n[11:03:44] event=evt_77b attempt=3 duplicate=false processing=complete`,
    apiRequest: `POST /webhooks/generation\nX-Event-Id: evt_77b\nX-Delivery-Attempt: 2\n\n{ "type": "generation.complete", "generation_id": "gen_441" }`,
    apiResponse: `HTTP/1.1 504 Gateway Timeout\nX-Handler-Duration: 8421ms`,
    deploymentDetails: `Gateway webhook timeout: 8s\nHandler: write CRM -> send email -> return 200\nIdempotency store: disabled`,
    environmentDetails: `WEBHOOK_ASYNC_PROCESSING=false\nWEBHOOK_IDEMPOTENCY_TTL=0\nCRM_WRITE_P95_MS=7100`,
    choices: ["The handler times out before acknowledging and has no event-level idempotency", "The webhook signature secret is incorrect", "The audio response is being parsed as JSON", "The Fly health path returns 404"], correctAnswer: 0,
    explanation: "The provider retries because it receives 504, while the side effect already completed. Without an idempotency record, every delivery repeats the work.",
    investigationSummary: { rootCause: "The webhook performed slow synchronous work before acknowledging and did not deduplicate retry deliveries.", evidence: ["First delivery completes its side effect but returns 504", "Every attempt uses the same event ID", "Idempotency storage is disabled"], impact: "The same completion event created duplicate CRM records.", resolution: "Persist the event ID, acknowledge quickly, move work to a queue, and reconcile duplicates created during the incident." },
    prevention: "Use idempotent webhook consumers, acknowledge before slow work, retain event IDs through the retry window, alert on repeat-delivery rates, and test timeout behavior.",
    customerFriendlyReply: "We found that the webhook provider retried events when our endpoint took too long to acknowledge them. We have added duplicate protection and moved the longer processing step out of the request path.",
  }),
  build({
    id: "malformed-json", incidentId: "INC-0017", title: "Agent tool request rejected before execution", product: "Conversational AI", severity: "Medium", category: "API", difficulty: "Foundational", error: "400 Invalid JSON",
    customerMessage: "Our appointment tool works in the test console, but production conversations fail whenever a caller gives a note containing quotation marks. The tool never reaches our scheduling service.",
    customerImpact: "Appointment booking fails for requests containing quoted free-text notes.",
    logs: `[12:31:09] tool=book_appointment request_id=tool_301 content_length=187\n[12:31:09] body_parse_failed offset=146 token=identifier\n[12:31:09] downstream_called=false status=400`,
    apiRequest: `POST /agent/tools/book\nContent-Type: application/json\n\n{ "date": "2026-07-08", "note": "Caller said "morning only"" }`,
    apiResponse: `{ "status": 400, "error": "invalid_json", "position": 146, "request_id": "tool_301" }`,
    deploymentDetails: `Release: v67\nChange: hand-built tool payload template\nPrevious release: JSON.stringify(toolArguments)`,
    environmentDetails: `TOOL_PAYLOAD_TEMPLATE=enabled\nSTRICT_JSON=true\nDownstream scheduler error rate=0%`,
    choices: ["Unescaped quotation marks make the generated tool payload invalid JSON", "The scheduling API key is missing", "The voice model is unsupported", "The agent exceeded its character quota"], correctAnswer: 0,
    explanation: "Parsing fails before any downstream call, and the failing payload contains unescaped quotes introduced by the new string template.",
    investigationSummary: { rootCause: "A custom string template inserted user text into JSON without escaping it.", evidence: ["Parser fails at the quotation mark", "The downstream service is never called", "The previous serializer safely handled the same input"], impact: "A subset of appointment tool calls failed before execution.", resolution: "Restore structured serialization, validate the schema before dispatch, and replay safe failed requests." },
    prevention: "Use JSON serializers instead of string templates, apply schema validation, fuzz tool arguments with special characters, and track parse failures separately from downstream errors.",
    customerFriendlyReply: "We identified an issue in how certain punctuation was encoded before the appointment tool ran. We corrected the request formatting and verified bookings with the affected note patterns.",
  }),
  build({
    id: "corrupted-audio", incidentId: "INC-0018", title: "Stored recordings develop clicks and missing frames", product: "ElevenLabs", severity: "High", category: "Audio Output", difficulty: "Escalation", error: "Invalid audio frame",
    customerMessage: "Freshly generated audio plays correctly in the preview, but files downloaded from our storage bucket contain clicks and stop early. Re-downloading produces the same damaged file.",
    customerImpact: "Archived production recordings are unusable even though live previews succeed.",
    logs: `[13:07:18] provider status=200 bytes=918244 sha256=31af…\n[13:07:18] storage_upload bytes=65536 sha256=82be… complete=true\n[13:08:02] decoder invalid_frame offset=65491`,
    apiRequest: `POST /v1/text-to-speech/voice_8\nAccept: audio/mpeg\n\n{ "text_length": 4220 }`,
    apiResponse: `HTTP/1.1 200 OK\nContent-Type: audio/mpeg\nContent-Length: 918244\nX-Request-Id: req_audio_81`,
    deploymentDetails: `Release v91 change: uploadBuffer = chunks[0]\nPrevious: uploadBuffer = Buffer.concat(chunks)\nObject store reports successful writes`,
    environmentDetails: `AUDIO_CHUNK_SIZE=65536\nPREVIEW_MODE=stream\nARCHIVE_MODE=buffered`,
    choices: ["Only the first response chunk is uploaded to object storage", "The provider generated corrupt MPEG data", "The API key is invalid", "CORS blocks the object download"], correctAnswer: 0,
    explanation: "The provider payload is complete and preview streaming works. Stored objects are exactly one chunk long and have a different checksum.",
    investigationSummary: { rootCause: "The archive path uploaded only the first binary chunk instead of the concatenated audio response.", evidence: ["Stored size equals one configured chunk", "Provider and storage checksums differ", "Live preview bypasses the broken buffering code"], impact: "Newly archived recordings were truncated and could not be decoded reliably.", resolution: "Concatenate all chunks before upload, verify length and checksum, regenerate affected recordings, and validate playback from storage." },
    prevention: "Assert content length and checksums, test multi-chunk recordings, verify stored playback after releases, and alarm on suspiciously uniform object sizes.",
    customerFriendlyReply: "The audio was generated correctly, but our storage step saved only part of each longer file. We fixed the upload path and are regenerating the affected recordings from their source text.", diagnosticProvider: "elevenlabs",
  }),
  build({
    id: "fly-memory-restart", incidentId: "INC-0019", title: "Voice worker restarts during concurrent exports", product: "Fly.io", severity: "Critical", category: "Infrastructure", difficulty: "Escalation", error: "Machine out of memory",
    customerMessage: "The export service becomes unavailable during our morning batch and recovers a minute later. Individual files succeed, but running several long voice exports together causes all in-flight jobs to disappear.",
    customerImpact: "Concurrent export batches are interrupted and must be restarted manually.",
    logs: `14:02:10 app memory=476MB jobs=6 buffered_audio=391MB\n14:02:13 kernel Out of memory: Killed process 321 (node)\n14:02:14 fly machine exited signal=SIGKILL oom_killed=true\n14:02:20 fly machine restarted`,
    apiRequest: `POST /api/exports/batch\n\n{ "jobs": 6, "average_characters": 24000 }`,
    apiResponse: `HTTP/2 502\nfly-error: instance unavailable\nrequest_id=edge_7701`,
    deploymentDetails: `Machine memory: 512MB\nConcurrency soft_limit: 20\nWorker buffers complete audio in memory\nSwap: disabled`,
    environmentDetails: `MAX_EXPORT_CONCURRENCY=8\nSTREAM_TO_STORAGE=false\nNODE_OPTIONS not set`,
    choices: ["Concurrent in-memory audio buffers exceed the Machine memory limit", "The Fly proxy uses the wrong internal port", "The API key belongs to staging", "The health endpoint returns 404"], correctAnswer: 0,
    explanation: "Memory rises with concurrent buffered exports until the kernel kills Node. The restart is a consequence, not the original failure.",
    investigationSummary: { rootCause: "The worker buffered several long audio files concurrently and exceeded its 512 MB memory allocation.", evidence: ["Kernel records an OOM kill", "Buffered audio accounts for most resident memory", "Single exports succeed while concurrent batches fail"], impact: "All jobs on the Machine were interrupted and the API briefly returned 502.", resolution: "Reduce worker concurrency, stream audio directly to storage, increase memory as a safety margin, and replay idempotent jobs." },
    prevention: "Stream large binaries, apply memory-aware concurrency, checkpoint jobs, alert on memory slope and OOM exits, and load-test production-sized exports.",
    customerFriendlyReply: "A batch of long exports exceeded the worker's available memory and caused it to restart. We reduced concurrent processing, switched the upload path to streaming, and safely resumed the interrupted jobs.",
  }),
  build({
    id: "fly-environment-mismatch", incidentId: "INC-0020", title: "Production agent calls staging tool endpoint", product: "Fly.io", severity: "High", category: "Configuration", difficulty: "Operational", error: "Resource not found",
    customerMessage: "Production conversations connect, but every account lookup says the customer cannot be found. The same account IDs work from our production API and in last week's deployment.",
    customerImpact: "Conversational agents cannot retrieve production account records.",
    logs: `[15:19:40] tool=lookup_account account=acct_901 request_id=tool_aa2\n[15:19:40] upstream_host=api.staging.example.net status=404\n[15:19:40] agent_environment=production`,
    apiRequest: `GET /v2/accounts/acct_901\nHost: api.staging.example.net\nAuthorization: Bearer [REDACTED]`,
    apiResponse: `{ "status": 404, "error": "account_not_found", "environment": "staging" }`,
    deploymentDetails: `Release v103 imported secrets from app-support-staging\nFly app: app-support-production\nImage digest unchanged from v102`,
    environmentDetails: `APP_ENV=production\nTOOL_API_BASE_URL=https://api.staging.example.net\nTOOL_API_KEY=[configured]`,
    choices: ["Production was deployed with the staging tool API base URL", "The production accounts were deleted", "The voice stream timed out", "The webhook signature was calculated from parsed JSON"], correctAnswer: 0,
    explanation: "The agent is healthy and authenticated, but request host and response metadata both point to staging, where production IDs do not exist.",
    investigationSummary: { rootCause: "A secret import copied the staging tool API base URL into the production Fly app.", evidence: ["Production logs show the staging hostname", "API response identifies the staging environment", "The release imported configuration from the staging app"], impact: "Production agent lookups returned false not-found responses.", resolution: "Restore the production endpoint, restart Machines, verify a known account, and audit other imported variables." },
    prevention: "Separate environment-scoped secret pipelines, validate host allowlists at startup, run post-deploy canaries with known records, and require review for cross-app secret imports.",
    customerFriendlyReply: "We found that the agent's account lookup was temporarily pointed at our staging data service. We restored the production connection and verified successful lookups with affected account IDs.",
  }),
  build({
    id: "deployment-regression", incidentId: "INC-0021", title: "Audio generation latency spikes after release", product: "Internal API", severity: "High", category: "Deployment", difficulty: "Escalation", error: "Latency regression",
    customerMessage: "Generation still succeeds, but response time increased from a few seconds to nearly a minute immediately after release 2.14. Rolling one Machine back appears to restore normal performance.",
    customerImpact: "Synchronous voice requests approach client timeouts and contact-center queues grow.",
    logs: `[16:00:02] release=2.14 request=req_210 provider_ms=3180 total_ms=48772\n[16:00:02] moderation_ms=45101 cache_hit=false\n[16:02:11] release=2.13 request=req_211 provider_ms=3290 total_ms=4012`,
    apiRequest: `POST /api/voice\nX-App-Release: 2.14\n\n{ "text": "Your delivery is confirmed" }`,
    apiResponse: `HTTP/1.1 200 OK\nServer-Timing: moderation;dur=45101, provider;dur=3180\nX-Total-Duration: 48772`,
    deploymentDetails: `v2.14: moderation client retry policy changed\nRetries: 3\nBackoff: 15s fixed\nv2.13: retries disabled for synchronous path`,
    environmentDetails: `MODERATION_ENDPOINT reachable=true\nMODERATION_TIMEOUT_MS=15000\nMODERATION_MAX_RETRIES=3`,
    choices: ["A new synchronous retry policy adds three 15-second moderation waits", "The voice provider is taking 48 seconds", "The Fly Machine is out of memory", "The browser is enforcing CORS"], correctAnswer: 0,
    explanation: "Provider duration remains normal. Server-Timing assigns nearly all added latency to the new moderation retry behavior, and rollback removes it.",
    investigationSummary: { rootCause: "Release 2.14 introduced blocking moderation retries with a fixed 15-second timeout.", evidence: ["Latency begins exactly with v2.14", "Provider time remains near baseline", "The moderation span contributes 45 seconds and rollback restores performance"], impact: "Requests succeeded slowly, threatening upstream client timeouts and live-call experience.", resolution: "Rollback v2.14, replace blocking retries with a bounded policy, and redeploy after latency tests." },
    prevention: "Set latency budgets per dependency, canary releases, compare Server-Timing by version, test failure paths, and automatically halt rollout on p95 regression.",
    customerFriendlyReply: "We traced the slowdown to a retry change in today's release, not to voice generation itself. We rolled back that change and confirmed response times have returned to their normal range.",
  }),
  build({
    id: "webhook-payload-validation", incidentId: "INC-0022", title: "New webhook event version fails schema validation", product: "ElevenLabs-style Webhook", severity: "Medium", category: "Webhook", difficulty: "Operational", error: "422 Validation Failed",
    customerMessage: "Conversation-ended webhooks stopped importing after we enabled the latest event version. Delivery is marked successful on the provider side, but our application records validation errors and creates no transcripts.",
    customerImpact: "New conversation transcripts are not imported into the customer analytics workspace.",
    logs: `[17:24:51] event=conversation.ended version=2026-06 id=evt_b92 signature=valid\n[17:24:51] validation_failed path=data.conversation_id expected=string received=undefined\n[17:24:51] legacy_field_present path=data.conversation.id`,
    apiRequest: `POST /webhooks/conversations\nX-Event-Version: 2026-06\n\n{ "type": "conversation.ended", "data": { "conversation": { "id": "conv_771" } } }`,
    apiResponse: `{ "status": 422, "error": "payload_validation_failed", "field": "data.conversation_id" }`,
    deploymentDetails: `Webhook endpoint release: v32\nAccepted schema: 2026-01\nProvider subscription version: 2026-06\nSignature verification: passing`,
    environmentDetails: `WEBHOOK_SCHEMA_VERSION=2026-01\nREJECT_UNKNOWN_VERSIONS=true\nDead-letter queue: enabled`,
    choices: ["The consumer validates the new nested payload against the older flat schema", "The signing secret is out of sync", "The event was delivered to staging", "The provider is rate limiting deliveries"], correctAnswer: 0,
    explanation: "Authenticity checks pass, but the new version nests the conversation ID. The consumer still requires the older flat field.",
    investigationSummary: { rootCause: "The webhook subscription moved to a new payload version before the consumer schema was updated.", evidence: ["Signature verification succeeds", "The event advertises version 2026-06", "The required ID moved from data.conversation_id to data.conversation.id"], impact: "Valid events entered the dead-letter queue and transcripts were delayed.", resolution: "Add version-aware parsing, deploy it, replay dead-lettered events idempotently, and verify transcript counts." },
    prevention: "Negotiate webhook versions explicitly, support schemas during migration windows, contract-test sample events, monitor dead-letter volume, and provide a replay runbook.",
    customerFriendlyReply: "The provider's newer event format did not match the version our importer expected. We added support for the updated format and replayed the delayed transcript events safely.",
  }),
  ...webInfrastructureIncidents,
];

export const getIncident = (id: string) => incidents.find((incident) => incident.id === id);

export const products = ["All products", ...Array.from(new Set(incidents.map((incident) => incident.product)))];
