import type { Incident } from "./types";

type WebIncidentInput = Omit<
  Incident,
  "status" | "level" | "apiRequest" | "apiResponse" | "customerContext" | "businessImpact"
> & {
  requestDetails: string;
  observedError: string;
  context?: Partial<Incident["customerContext"]>;
};

const webIncident = ({ context, ...incident }: WebIncidentInput): Incident => ({
  ...incident,
  status: "Open",
  level: incident.difficulty,
  customerContext: {
    customer: "Managed website account",
    plan: incident.severity === "Critical" ? "Business Critical" : "Managed Hosting",
    environment: "Production",
    affectedUsers: incident.severity === "Critical" ? "All website visitors" : "A subset of visitors or administrators",
    region: "Global",
    started: "Reported today",
    ...context,
  },
  businessImpact: {
    serviceImpact: incident.customerImpact,
    estimatedAffectedUsers: incident.severity === "Critical" ? "All active visitors" : "Traffic and staff using the affected workflow",
    businessImpact: incident.severity === "Critical" ? "Public website or a core business channel unavailable" : "Customer-facing workflow degraded and support contacts increasing",
    priority: incident.severity === "Critical" ? "P1 — Critical" : incident.severity === "High" ? "P2 — High" : "P3 — Standard",
    revenueImpact: incident.severity === "Critical" || incident.severity === "High" ? "Leads, orders, or operational work may be delayed" : "No direct revenue loss confirmed",
  },
});

export const webInfrastructureIncidents: Incident[] = [
  webIncident({
    id: "wordpress-plugin-update-502", incidentId: "INC-0023", title: "WordPress 502 after plugin update", product: "WordPress", severity: "Critical", category: "WordPress", difficulty: "Operational", error: "502 Bad Gateway",
    customerMessage: "Hi Support, our storefront started showing a 502 shortly after routine plugin updates. The homepage sometimes loads from cache, but wp-admin and checkout do not.",
    customerImpact: "Administrators cannot access WordPress and uncached storefront requests fail.",
    logs: `[10:14:02] php-fpm child 882 said: PHP Fatal error: Uncaught TypeError in /wp-content/plugins/catalog-sync/includes/client.php:214\n[10:14:02] nginx upstream prematurely closed connection while reading response header\n[10:14:03] GET /wp-admin/ 502 0.184s`,
    requestDetails: `GET /wp-admin/ HTTP/2\nHost: shop.example.test\nCache-Status: BYPASS\n\nRecent change: catalog-sync 4.8.1 → 4.9.0 at 10:12 UTC`,
    observedError: `HTTP/2 502 Bad Gateway\nserver: nginx\n\nCached homepage: 200\nUncached PHP routes: 502`,
    deploymentDetails: `WordPress core: 6.8.1\nPHP-FPM: running\nNginx: healthy\nPlugin auto-update completed with no deployment rollback`,
    environmentDetails: `PHP=8.2\nWP_DEBUG_LOG=true\nACTIVE_THEME=custom-storefront\nObject cache reachable=true`,
    timeline: [{ time: "10:12 UTC", event: "Plugin update completes" }, { time: "10:14 UTC", event: "Uncached requests begin returning 502" }, { time: "10:23 UTC", event: "Support correlates PHP fatal errors with the updated plugin" }, { time: "10:31 UTC", event: "Plugin rollback restores wp-admin and checkout" }],
    notes: "A 502 only shows that the proxy lost its upstream. Correlate the first PHP fatal with the update and test uncached routes before changing Nginx.",
    choices: ["The plugin update introduced a PHP fatal error", "The domain A record still points to the old server", "Cloudflare is rate limiting wp-admin", "The database storage engine is read-only"], correctAnswer: 0,
    explanation: "The proxy and PHP-FPM remain available, but every uncached request reaches the same fatal code path immediately after the plugin update. Cache explains the occasional successful homepage.",
    investigationSummary: { rootCause: "A plugin update introduced a PHP fatal error that caused PHP-FPM responses to terminate before Nginx received headers.", evidence: ["Fatal stack trace names the updated plugin", "Failures begin two minutes after its update", "Cached pages work while uncached PHP routes fail"], impact: "Dynamic storefront and administration routes returned 502.", resolution: "Disable or roll back the plugin, confirm critical routes, then test a compatible release in staging." },
    prevention: "Stage plugin updates, retain rollback packages, monitor PHP fatals, and smoke-test uncached business-critical routes after changes.",
    customerFriendlyReply: "We traced the outage to an incompatibility introduced by the latest plugin update. We rolled back that update and confirmed the storefront, checkout, and administration area are responding normally again.",
  }),
  webIncident({
    id: "wordpress-white-screen", incidentId: "INC-0024", title: "WordPress white screen of death", product: "WordPress", severity: "High", category: "WordPress", difficulty: "Foundational", error: "Blank page with HTTP 500",
    customerMessage: "The site is only showing a blank white page. There is no visible error, and we can reach the hosting control panel but not the website or wp-admin.",
    customerImpact: "The public site and WordPress administration screen render no usable content.",
    logs: `[07:42:11] PHP Fatal error: Cannot redeclare format_event_date() in /wp-content/plugins/event-calendar-pro/functions.php:88\n[07:42:11] GET / 500 bytes=0\n[07:42:18] GET /wp-admin/ 500 bytes=0`,
    requestDetails: `Browser request: GET /\nResponse body length: 0 bytes\nStatic file check: GET /wp-content/uploads/logo.png → 200`,
    observedError: `HTTP/2 500 Internal Server Error\ncontent-length: 0\n\nBrowser displays a blank document because display_errors is disabled.`,
    deploymentDetails: `No core deployment today\nPlugin event-calendar-pro enabled at 07:39 UTC\nTheme files unchanged for 18 days`,
    environmentDetails: `PHP=8.1\ndisplay_errors=Off\nWP_DEBUG=false\nRecovery email delivery=delayed`,
    timeline: [{ time: "07:39 UTC", event: "Event plugin is activated" }, { time: "07:42 UTC", event: "Public and admin PHP pages return empty 500 responses" }, { time: "07:51 UTC", event: "Server log reveals duplicate function declaration" }, { time: "08:03 UTC", event: "Plugin is disabled and pages recover" }],
    notes: "Do not enable display_errors on a public production site. Use server-side PHP logs and a safe plugin-disable method instead.",
    choices: ["An incompatible plugin triggers a fatal PHP error", "The browser has stale DNS", "The SSL certificate is expired", "The uploads directory is not writable"], correctAnswer: 0,
    explanation: "Static assets load, while all PHP routes return an empty 500. The server log identifies a fatal duplicate declaration in event-calendar-pro immediately after that plugin was activated.",
    investigationSummary: { rootCause: "The event-calendar-pro plugin caused a fatal PHP error before WordPress could render a response.", evidence: ["Both frontend and wp-admin return empty 500 responses", "Static assets remain available", "PHP log identifies event-calendar-pro immediately after activation"], impact: "The entire WordPress application appeared as a blank page.", resolution: "Disable event-calendar-pro outside wp-admin, confirm the site recovers, and replace or update the plugin before re-enabling it." },
    prevention: "Test plugins against the production PHP and WordPress versions, keep server-side error logging enabled, and document emergency plugin deactivation.",
    customerFriendlyReply: "We found that the event-calendar-pro plugin was triggering a fatal error that prevented WordPress from loading. We disabled the affected plugin and confirmed the website and administration area are available again. Before re-enabling it, we recommend updating it to a compatible version or replacing it to prevent recurrence.",
  }),
  webIncident({
    id: "wordpress-maintenance-mode", incidentId: "INC-0025", title: "WordPress stuck in maintenance mode", product: "WordPress", severity: "Medium", category: "WordPress", difficulty: "Foundational", error: "Briefly unavailable for scheduled maintenance",
    customerMessage: "The maintenance message has been on the site for almost an hour even though the update screen was closed. We need the site back before a campaign starts.",
    customerImpact: "Visitors and administrators see the WordPress maintenance message instead of the site.",
    logs: `[15:02:08] core update download complete\n[15:02:10] process terminated: control panel session timeout\n[15:46:31] GET / 503 maintenance_mode=true\n[15:46:31] wp-cron heartbeat completed`,
    requestDetails: `WordPress root listing:\n.maintenance  92 bytes  modified 15:02 UTC\nwp-config.php\nwp-content/\n\nNo update process is currently running.`,
    observedError: `HTTP/2 503 Service Unavailable\n\nBriefly unavailable for scheduled maintenance. Check back in a minute.`,
    deploymentDetails: `Core update initiated through hosting panel\nSession ended before cleanup step\nCurrent WordPress files pass checksum verification`,
    environmentDetails: `Filesystem writable=true\nPHP workers healthy\nDatabase reachable=true\nMaintenance file age=46 minutes`,
    timeline: [{ time: "15:02 UTC", event: "Update begins and creates .maintenance" }, { time: "15:03 UTC", event: "Control-panel process ends unexpectedly" }, { time: "15:41 UTC", event: "Customer reports persistent maintenance page" }, { time: "15:49 UTC", event: "Stale file is removed after update integrity checks" }],
    notes: "Confirm no updater is running and validate core/plugin integrity before removing the maintenance marker.",
    choices: ["A failed update left the .maintenance file in the WordPress root", "The origin certificate expired", "PHP memory is exhausted", "Cloudflare cached a 301 redirect"], correctAnswer: 0,
    explanation: "The update process ended before cleanup, no updater remains active, and the old .maintenance marker continues to trigger the standard response.",
    investigationSummary: { rootCause: "An interrupted update left the .maintenance file in the WordPress root directory.", evidence: ["Standard WordPress maintenance response", "Stale .maintenance file matches the interruption time", "No update process is still running"], impact: "WordPress intentionally returned maintenance mode to every request.", resolution: "Verify update integrity, remove the stale .maintenance file, clear page caches, and complete any pending update safely." },
    prevention: "Run updates through a durable process, monitor completion, keep backups, and alert when maintenance mode persists beyond the expected window.",
    customerFriendlyReply: "The update process ended before WordPress removed its maintenance marker. We verified the update files, cleared the stale marker, and confirmed the site is available again.",
  }),
  webIncident({
    id: "wordpress-database-credentials", incidentId: "INC-0026", title: "WordPress database connection error", product: "WordPress", severity: "Critical", category: "WordPress", difficulty: "Operational", error: "Error establishing a database connection",
    customerMessage: "After moving the database to the new hosting account, WordPress says it cannot connect. The database appears online in the control panel.",
    customerImpact: "All dynamic WordPress pages and wp-admin are unavailable.",
    logs: `[18:20:04] mysqli_real_connect(): Access denied for user 'wp_app_old'@'10.0.4.18'\n[18:20:04] wordpress db_connect_error host=db.internal\n[18:21:10] database health probe with new user: ok`,
    requestDetails: `wp-config.php (values redacted):\nDB_NAME=site_prod\nDB_USER=wp_app_old\nDB_HOST=db.internal\n\nHosting panel lists authorized user: wp_app_prod`,
    observedError: `HTTP/2 500\n\nError establishing a database connection\nDatabase service health: available`,
    deploymentDetails: `Database migration completed 18:12 UTC\nApplication files copied from previous host\nwp-config.php preserved from source server`,
    environmentDetails: `Database port reachable=true\nDatabase name exists=true\nConfigured username matches authorized user=false\nCredentials are redacted`,
    timeline: [{ time: "18:12 UTC", event: "Database import completes" }, { time: "18:18 UTC", event: "DNS preview is switched to the new host" }, { time: "18:20 UTC", event: "WordPress logs access denied for the old database user" }, { time: "18:34 UTC", event: "Configuration is corrected and application health verified" }],
    notes: "A reachable database is not proof that application credentials are valid. Compare redacted identifiers without requesting passwords in a ticket.",
    choices: ["wp-config.php contains the previous host's database credentials", "The DNS TTL has not expired", "A page cache contains the database error", "The theme requires a newer PHP version"], correctAnswer: 0,
    explanation: "Network and database health checks pass, but WordPress authenticates as an old user that the migrated database does not authorize.",
    investigationSummary: { rootCause: "Incorrect database credentials remained in wp-config.php after migration.", evidence: ["Database service and port are healthy", "Access-denied log names the old application user", "Hosting panel authorizes a different production user"], impact: "WordPress could not read content or sessions from its database.", resolution: "Update the server-side database configuration securely, test wp-admin and public pages, and rotate any temporary migration credentials." },
    prevention: "Use a migration checklist for environment-specific configuration, validate credentials before DNS cutover, and store secrets outside shared tickets.",
    customerFriendlyReply: "The website was still using the previous server's database login after migration. We corrected the protected configuration and confirmed that the public site and administration area can connect normally.",
  }),
  webIncident({
    id: "wordpress-media-permissions", incidentId: "INC-0027", title: "WordPress media upload failing", product: "WordPress", severity: "Medium", category: "WordPress", difficulty: "Operational", error: "Unable to create directory uploads/2026/07",
    customerMessage: "Editors can log in and update text, but every new image upload fails. Existing images still display and there is plenty of account storage.",
    customerImpact: "Content editors cannot publish new media while existing website content remains available.",
    logs: `[09:08:17] wp_handle_upload error="Unable to create directory wp-content/uploads/2026/07"\n[09:08:17] php-fpm uid=www-data gid=www-data\n[09:09:02] filesystem write test /tmp: ok`,
    requestDetails: `POST /wp-admin/async-upload.php\nFile: campaign-banner.webp (428 KB)\nUser role: Editor\n\nwp-content/uploads owner=deploy:deploy mode=0755`,
    observedError: `HTTP/2 200\nWordPress JSON error: "The uploaded file could not be moved to wp-content/uploads/2026/07."`,
    deploymentDetails: `Files restored from backup by root-owned deployment job\nApplication code healthy\nDisk usage: 43%`,
    environmentDetails: `PHP upload_max_filesize=16M\npost_max_size=20M\nUpload size=428K\nPHP-FPM user cannot write uploads=true`,
    timeline: [{ time: "08:40 UTC", event: "Backup restoration completes" }, { time: "09:03 UTC", event: "Editor reports failed upload" }, { time: "09:12 UTC", event: "Support rules out size and disk limits" }, { time: "09:20 UTC", event: "Ownership is corrected and upload retested" }],
    notes: "Avoid broad 777 permissions. Match the uploads directory owner/group to the web process and apply the narrowest writable mode.",
    choices: ["Uploads directory ownership prevents the PHP worker from writing", "The media file exceeds PHP limits", "The database password is invalid", "The domain points to the old server"], correctAnswer: 0,
    explanation: "The file is far below upload limits and disk space is available. The restored directory is owned by a deployment user and is not writable by PHP-FPM.",
    investigationSummary: { rootCause: "Incorrect ownership on wp-content/uploads prevented the PHP process from creating the monthly directory.", evidence: ["WordPress reports a filesystem move failure", "Upload and disk limits are healthy", "Uploads owner differs from the PHP-FPM user"], impact: "Editors could not add new media files.", resolution: "Correct uploads ownership and safe directory permissions, then verify uploads and thumbnail generation." },
    prevention: "Preserve ownership in backup restores, verify writable paths after deployments, and prohibit blanket world-writable permissions.",
    customerFriendlyReply: "The restored media folder had ownership settings that prevented WordPress from saving new files. We corrected those settings safely and confirmed image uploads and thumbnail creation are working.",
  }),
  webIncident({
    id: "dns-old-server", incidentId: "INC-0028", title: "DNS domain points to old server", product: "DNS", severity: "High", category: "DNS", difficulty: "Foundational", error: "Domain resolves to retired origin",
    customerMessage: "The migration preview looked correct, but the public domain still shows the old website. Clearing the browser cache did not change it.",
    customerImpact: "Visitors continue reaching the old hosting environment after migration.",
    logs: `[11:30:14] new-origin access log: no requests for Host www.example.test\n[11:31:02] old-origin GET / 200 host=www.example.test\n[11:32:09] authoritative query A example.test → 192.0.2.41`,
    requestDetails: `Authoritative DNS:\nexample.test. 300 IN A 192.0.2.41\nwww.example.test. 300 IN CNAME example.test.\n\nNew hosting IP: 198.51.100.27`,
    observedError: `Expected origin: 198.51.100.27\nObserved origin: 192.0.2.41\nHTTP response is valid but contains the pre-migration release marker.`,
    deploymentDetails: `New host migration: complete\nNew-origin hosts-file test: passed\nOld hosting account: still active during cutover`,
    environmentDetails: `Registrar nameservers match DNS provider=true\nA record last modified=94 days ago\nProxy/CDN disabled\nTTL=300`,
    timeline: [{ time: "09:00 UTC", event: "Migration validation passes using a hosts-file override" }, { time: "11:15 UTC", event: "Customer reports public domain still shows old site" }, { time: "11:32 UTC", event: "Authoritative A record is compared with new hosting IP" }, { time: "11:38 UTC", event: "A record is corrected and resolution monitored" }],
    notes: "A hosts-file preview bypasses public DNS. Check authoritative answers before attributing the old site to browser or CDN cache.",
    choices: ["The authoritative A record still contains the old server IP", "DNS propagation is incomplete after a correct update", "The new server has a PHP fatal error", "The TLS certificate lacks the www name"], correctAnswer: 0,
    explanation: "The authoritative DNS response itself returns the old address, and requests appear only in the old origin logs. No recent DNS update exists to propagate.",
    investigationSummary: { rootCause: "The domain A record still pointed to the old server instead of the new hosting IP.", evidence: ["Authoritative DNS returns the old IP", "Old origin receives public requests", "New origin works only with a hosts-file override"], impact: "Public visitors remained on the old site after migration.", resolution: "Update the authoritative A record, verify root and www records, monitor multiple resolvers, and retire the old host only after traffic drains." },
    prevention: "Document DNS cutover values, lower TTL before migrations, verify authoritative records, and keep the old host available through the rollback window.",
    customerFriendlyReply: "The website migration was complete, but the public domain was still directing visitors to the previous server. We corrected the DNS record and are monitoring the transition as cached entries expire.",
  }),
  webIncident({
    id: "dns-propagation-cache", incidentId: "INC-0029", title: "DNS propagation confusion", product: "DNS", severity: "Medium", category: "DNS", difficulty: "Operational", error: "Resolvers return different A records",
    customerMessage: "The new site loads on mobile data, but our office and a few customers still reach the previous server. The DNS dashboard already shows the new address.",
    customerImpact: "Visitors receive different site versions depending on their recursive DNS resolver.",
    logs: `[13:05:00] authoritative A example.test → 198.51.100.27 TTL=300\n[13:06:14] resolver 1.1.1.1 → 198.51.100.27\n[13:06:20] office resolver → 192.0.2.41 remaining_ttl=1840`,
    requestDetails: `Record changed at 12:48 UTC\nPrevious TTL before change: 3600 seconds\nCurrent authoritative TTL: 300 seconds\nOld server remains reachable`,
    observedError: `Public resolver comparison:\nResolver A → new IP\nResolver B → new IP\nOffice resolver → old IP with cached TTL remaining`,
    deploymentDetails: `Both origins healthy during propagation window\nNew site release marker verified\nNo Cloudflare proxy in path`,
    environmentDetails: `Authoritative nameservers agree=true\nDNSSEC status=valid\nOffice recursive cache flush unavailable\nElapsed since change=18 minutes`,
    timeline: [{ time: "12:48 UTC", event: "A record changes to the new origin" }, { time: "13:01 UTC", event: "Mobile traffic begins reaching new site" }, { time: "13:06 UTC", event: "Office resolver still reports old cached answer" }, { time: "13:49 UTC", event: "Resolver expires old value and converges" }],
    notes: "The new TTL applies to future lookups; caches may retain the earlier record for the previous TTL duration.",
    choices: ["Some recursive resolvers still cache the pre-change record", "The authoritative A record was never updated", "Cloudflare has blocked the office IP", "WordPress permalinks need to be flushed"], correctAnswer: 0,
    explanation: "Authoritative servers agree on the new value, while one recursive resolver reports the old value with time remaining from the earlier one-hour TTL.",
    investigationSummary: { rootCause: "DNS records were updated correctly, but some networks still cached the previous value under the old TTL.", evidence: ["Authoritative nameservers return the new IP", "Most public resolvers have converged", "Office resolver exposes an unexpired old cached answer"], impact: "Visitors temporarily reached different origins.", resolution: "Keep both origins safe during the TTL window, wait for caches to expire, and verify convergence across representative resolvers." },
    prevention: "Lower TTL well before cutover, record the previous TTL, avoid premature server shutdown, and communicate the expected cache window.",
    customerFriendlyReply: "The DNS change is correct, but a small number of networks are still using the previous cached address. Those entries are expiring normally, and we are keeping both servers available while the transition completes.",
  }),
  webIncident({
    id: "cloudflare-flexible-loop", incidentId: "INC-0030", title: "Cloudflare Flexible SSL redirect loop", product: "Cloudflare", severity: "High", category: "Cloudflare", difficulty: "Operational", error: "ERR_TOO_MANY_REDIRECTS",
    customerMessage: "After enabling Cloudflare, the browser says the site redirected too many times. Pausing the proxy makes the HTTPS site load normally.",
    customerImpact: "All proxied website visits fail before WordPress content loads.",
    logs: `[16:14:20] edge visitor_scheme=https origin_scheme=http\n[16:14:20] origin GET / forwarded_proto=http → 301 https://example.test/\n[16:14:21] redirect repeated count=12`,
    requestDetails: `Cloudflare SSL/TLS mode: Flexible\nAlways Use HTTPS: enabled\nOrigin rule: redirect HTTP to HTTPS\nOrigin certificate: valid`,
    observedError: `Browser: ERR_TOO_MANY_REDIRECTS\nRedirect chain repeats https://example.test/\nEdge-to-origin request continues over HTTP.`,
    deploymentDetails: `Cloudflare proxy enabled at 16:09 UTC\nOrigin HTTPS verified directly before proxy cutover\nNo WordPress plugin changes`,
    environmentDetails: `Edge HTTPS=true\nOrigin HTTPS=true\nCloudflare origin scheme under Flexible=http\nHSTS disabled during investigation`,
    timeline: [{ time: "16:09 UTC", event: "Cloudflare proxy is enabled in Flexible mode" }, { time: "16:12 UTC", event: "First redirect-loop report arrives" }, { time: "16:20 UTC", event: "Edge and origin schemes are compared" }, { time: "16:27 UTC", event: "Mode changes to Full (strict) and loop clears" }],
    notes: "Do not remove origin HTTPS enforcement as the long-term fix when the origin already has a valid certificate; align the edge-to-origin scheme.",
    choices: ["Flexible mode uses HTTP to an origin that redirects HTTP to HTTPS", "The browser cached the old server IP", "The origin certificate has expired", "The WordPress database URL uses HTTP"], correctAnswer: 0,
    explanation: "The visitor connects securely to Cloudflare, but Flexible mode repeats an HTTP origin request. The origin correctly redirects that request to HTTPS, creating the loop.",
    investigationSummary: { rootCause: "Cloudflare Flexible SSL conflicted with the origin's HTTPS redirect policy.", evidence: ["Loop begins when proxy is enabled", "Edge logs show HTTPS visitor but HTTP origin scheme", "Direct origin HTTPS and certificate are healthy"], impact: "Proxied visitors could not reach any page.", resolution: "Set Cloudflare to Full (strict), retain origin HTTPS, purge relevant redirect cache, and verify the complete redirect chain." },
    prevention: "Use Full (strict) with a valid origin certificate, document TLS ownership, and test redirects before enabling proxy traffic.",
    customerFriendlyReply: "The secure connection settings between Cloudflare and the hosting server did not match, which created a redirect loop. We aligned those settings and confirmed the site now loads securely.",
  }),
  webIncident({
    id: "cloudflare-522-origin-timeout", incidentId: "INC-0031", title: "Cloudflare 522 connection timed out", product: "Cloudflare", severity: "Critical", category: "Cloudflare", difficulty: "Escalation", error: "522 Connection timed out",
    customerMessage: "Cloudflare shows error 522 for the website. DNS looks active, and the server dashboard says the machine is running, but we cannot load the origin directly either.",
    customerImpact: "The public website is unavailable through Cloudflare and direct origin tests.",
    logs: `[03:18:01] cloudflare edge connect origin=198.51.100.44:443 timeout\n[03:18:04] origin firewall DROP src=Cloudflare-range dst_port=443\n[03:19:11] ssh health: load=0.21 nginx=active`,
    requestDetails: `DNS A record → 198.51.100.44 (proxied)\nTCP 443 from external probe → timeout\nTCP 443 from localhost → accepted\nRecent firewall policy applied at 03:12 UTC`,
    observedError: `Cloudflare Ray: synthetic-redacted\nError 522: Connection timed out\nOrigin did not complete a TCP connection from the edge.`,
    deploymentDetails: `Web service unchanged\nFirewall allowlist regenerated during security maintenance\nCloudflare address ranges absent from new policy`,
    environmentDetails: `Origin CPU=14%\nNginx active=true\nDisk=51%\nPorts 80/443 blocked for edge ranges=true`,
    timeline: [{ time: "03:12 UTC", event: "New origin firewall rules are applied" }, { time: "03:17 UTC", event: "Cloudflare 522 rate spikes" }, { time: "03:25 UTC", event: "Service health is separated from external reachability" }, { time: "03:34 UTC", event: "Edge ranges are restored and traffic recovers" }],
    notes: "A running server is not necessarily reachable. Test TCP connectivity from outside and correlate firewall changes before restarting services.",
    choices: ["The origin firewall blocks Cloudflare from reaching HTTP/HTTPS", "Cloudflare DNS points to an old but healthy server", "Flexible SSL creates an application redirect loop", "WordPress exhausted PHP memory"], correctAnswer: 0,
    explanation: "The origin service accepts local connections and has spare resources, but external TCP connections time out and firewall logs show dropped edge addresses after a policy change.",
    investigationSummary: { rootCause: "A firewall update removed the Cloudflare IP ranges, so the origin did not respond to edge connections on ports 80/443.", evidence: ["Cloudflare reports connection timeout rather than HTTP failure", "Nginx is healthy locally", "Firewall drops coincide with the new policy"], impact: "Cloudflare could not connect to the otherwise healthy origin.", resolution: "Restore trusted edge ranges, verify ports 80/443 externally, monitor 522 rates, and review the firewall generation process." },
    prevention: "Manage edge allowlists from an authoritative source, validate external reachability after firewall changes, and keep console access for recovery.",
    customerFriendlyReply: "The hosting server remained healthy, but a firewall update prevented Cloudflare from reaching it. We restored the required network access and confirmed the website is responding globally again.",
  }),
  webIncident({
    id: "cloudflare-526-origin-certificate", incidentId: "INC-0032", title: "Cloudflare 526 invalid SSL certificate", product: "Cloudflare", severity: "High", category: "Cloudflare", difficulty: "Operational", error: "526 Invalid SSL certificate",
    customerMessage: "The site stopped loading through Cloudflare after we changed SSL mode to Full Strict. It works if strict validation is disabled, but we want to keep the secure setting.",
    customerImpact: "HTTPS requests through Cloudflare fail certificate validation at the origin.",
    logs: `[05:40:14] edge tls origin handshake failed verify_error=certificate has expired\n[05:40:14] origin=198.51.100.63 sni=example.test\n[05:42:01] direct openssl notAfter=Jul 05 23:59:59 2026 GMT`,
    requestDetails: `Cloudflare SSL mode: Full (strict)\nOrigin certificate subject: example.test\nCertificate chain: present\nCurrent time: Jul 06 05:42 UTC`,
    observedError: `HTTP/2 526\nCloudflare: Invalid SSL certificate\nOrigin TLS inspection: certificate expired approximately six hours ago.`,
    deploymentDetails: `No application deployment\nCertificate renewal job attempted Jul 05\nACME validation returned 403 for /.well-known/acme-challenge/`,
    environmentDetails: `Origin port 443 reachable=true\nSNI matches=true\nCertificate expired=true\nCloudflare edge certificate valid=true`,
    timeline: [{ time: "Jul 05 23:59 UTC", event: "Origin certificate expires" }, { time: "05:35 UTC", event: "Cloudflare mode changes to Full (strict)" }, { time: "05:40 UTC", event: "526 responses begin" }, { time: "06:02 UTC", event: "Origin certificate renews and strict validation succeeds" }],
    notes: "Do not weaken strict validation as the permanent fix. Repair the origin certificate and its renewal path.",
    choices: ["Full Strict rejects the expired origin certificate", "Cloudflare cannot resolve the DNS record", "The origin firewall blocks edge connections", "WordPress redirects HTTP to HTTPS"], correctAnswer: 0,
    explanation: "Network connectivity and SNI are correct. Strict mode exposes the expired origin certificate, while the separate edge certificate remains valid.",
    investigationSummary: { rootCause: "Cloudflare Full (strict) rejected an expired origin SSL certificate after automated renewal failed.", evidence: ["526 begins under strict validation", "Origin TLS inspection shows an expired date", "Edge certificate and origin connectivity remain healthy"], impact: "Cloudflare refused to proxy HTTPS traffic to the origin.", resolution: "Renew and install a valid origin certificate, correct ACME validation, retain Full (strict), and retest the certificate chain." },
    prevention: "Alert well before origin expiry, monitor renewal jobs and ACME paths, and regularly test strict edge-to-origin TLS.",
    customerFriendlyReply: "Cloudflare correctly detected that the hosting server's certificate had expired. We renewed the origin certificate, repaired its automatic renewal check, and confirmed strict secure connections are working.",
  }),
  webIncident({
    id: "hosting-disk-full", incidentId: "INC-0033", title: "Hosting disk full", product: "Hosting", severity: "High", category: "Hosting", difficulty: "Foundational", error: "No space left on device",
    customerMessage: "Image uploads, backups, and cache updates all started failing this morning. The site still loads, but new orders occasionally show a generic save error.",
    customerImpact: "Writes fail across multiple website functions and transaction reliability is at risk.",
    logs: `[06:11:44] PHP Warning: file_put_contents(): No space left on device\n[06:11:46] backup archive write failed errno=28\n[06:12:01] database temp table creation failed disk_full`,
    requestDetails: `Filesystem /home usage: 100%\nLargest paths:\nbackups/ 31 GB\nwp-content/cache/ 14 GB\nlogs/ 8 GB\nLast successful backup rotation: 19 days ago`,
    observedError: `Media: "Unable to write file to disk"\nBackup: ENOSPC\nCache: write failed\nRead-only page requests may still return 200.`,
    deploymentDetails: `No application release\nNightly backups stored on same hosting volume\nRetention job failing silently`,
    environmentDetails: `Disk quota=60 GB\nUsed=60 GB\nInodes=62%\nDatabase service running with write warnings`,
    timeline: [{ time: "01:00 UTC", event: "Nightly backup consumes remaining capacity" }, { time: "06:11 UTC", event: "Uploads and cache writes fail" }, { time: "06:20 UTC", event: "Support correlates failures across writable paths" }, { time: "06:42 UTC", event: "Safe cleanup restores headroom and writes are verified" }],
    notes: "Preserve recent backups and investigate growth before deleting data. Free temporary headroom first, then fix retention.",
    choices: ["The hosting account has exhausted its disk allocation", "The uploads directory has the wrong owner", "PHP memory is exhausted", "The DNS resolver cached the old site"], correctAnswer: 0,
    explanation: "Unrelated write paths fail with ENOSPC while reads continue. Capacity data and failed backup rotation explain the shared boundary.",
    investigationSummary: { rootCause: "Unrotated backups and cache growth exhausted the hosting disk quota.", evidence: ["Filesystem reports 100% usage", "Multiple services return no-space errors", "Backup retention stopped before sustained growth"], impact: "Uploads, caches, backups, and some database writes failed.", resolution: "Free space safely, move or prune backups under policy, clear regenerable cache, verify database integrity, and restore retention." },
    prevention: "Alert on disk trends, store backups off-host, test retention jobs, reserve emergency capacity, and monitor both bytes and inodes.",
    customerFriendlyReply: "The hosting account reached its storage limit because older backups were not rotating as expected. We restored safe capacity, verified website writes, and corrected the retention process.",
  }),
  webIncident({
    id: "php-memory-exhausted", incidentId: "INC-0034", title: "PHP memory exhausted", product: "Hosting", severity: "High", category: "Hosting", difficulty: "Operational", error: "Allowed memory size exhausted",
    customerMessage: "Most pages work, but the product export and one large wp-admin report fail with a 500. Smaller exports still complete.",
    customerImpact: "Administrators cannot generate large reports or exports; normal browsing remains available.",
    logs: `[12:02:17] export rows=18422 memory=126MB\n[12:02:18] PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 16777224 bytes)\n[12:02:18] POST /wp-admin/admin-post.php?action=export 500`,
    requestDetails: `Operation: product CSV export\nSelected rows: 18,422\nSmall export: 1,000 rows → success\nPlugin loads complete result set before writing CSV`,
    observedError: `HTTP/2 500\nPHP worker terminated during export\nNo provider or network error recorded.`,
    deploymentDetails: `Reporting plugin updated one day ago\nNew version adds image metadata to export\nNo hosting plan change`,
    environmentDetails: `memory_limit=128M\nmax_execution_time=120\nWorker peak before failure=126M\nAvailable server RAM=healthy`,
    timeline: [{ time: "11:52 UTC", event: "Administrator starts full product export" }, { time: "12:02 UTC", event: "PHP worker reaches 128 MB limit" }, { time: "12:12 UTC", event: "Support confirms size-dependent failure" }, { time: "12:36 UTC", event: "Export is batched and completes within bounded memory" }],
    notes: "Raising memory may provide temporary relief, but the durable fix is bounded processing for data-size-dependent work.",
    choices: ["The export exceeds the configured PHP memory limit", "The hosting disk is full", "The database password changed", "Cloudflare times out before reaching PHP"], correctAnswer: 0,
    explanation: "The fatal reports the exact 128 MB boundary, failures scale with export size, and the plugin loads the full dataset into memory.",
    investigationSummary: { rootCause: "The reporting plugin exceeded PHP's 128 MB memory limit while loading a large export into memory.", evidence: ["Fatal error names the allowed memory boundary", "Small exports succeed", "Peak memory rises with the selected row count"], impact: "Large administrative exports returned 500.", resolution: "Process exports in batches or streams, apply a justified temporary memory adjustment, and verify production-sized jobs." },
    prevention: "Load-test large datasets, use streaming exports, monitor PHP worker memory, and review plugin resource changes before updates.",
    customerFriendlyReply: "The full report was using more memory than the server allows because it loaded all records at once. We changed the export to process the data in smaller batches and confirmed it now completes successfully.",
  }),
  webIncident({
    id: "hosting-cron-failed", incidentId: "INC-0035", title: "Cron job failed", product: "Hosting", severity: "Medium", category: "Hosting", difficulty: "Escalation", error: "Scheduled tasks overdue",
    customerMessage: "Scheduled posts and subscription emails stopped going out overnight. Publishing manually works, and the website otherwise looks healthy.",
    customerImpact: "Time-sensitive publishing and background email jobs remain queued.",
    logs: `[00:00:01] system cron command=/usr/bin/php /home/site/public/wp-cron.php exit=1\n[00:00:01] stderr="Could not open input file: /home/site/public/wp-cron.php"\n[08:15:22] wp cron event newsletter_send overdue_by=29422s`,
    requestDetails: `Hosting migration changed document root:\nOld: /home/site/public\nCurrent: /home/site/public_html\nDISABLE_WP_CRON=true\nLoopback test: 403 from security rule`,
    observedError: `Scheduled event dashboard:\nnewsletter_send — overdue\npublish_future_post — overdue\nSystem cron target path does not exist.`,
    deploymentDetails: `Hosting migration completed yesterday\nSystem cron definition copied without path update\nApplication requests and database healthy`,
    environmentDetails: `System cron enabled=true\nWP pseudo-cron disabled=true\nCron PHP binary exists=true\nConfigured script path exists=false`,
    timeline: [{ time: "Yesterday 19:00 UTC", event: "Website moves to new document root" }, { time: "00:00 UTC", event: "Copied cron command fails on old path" }, { time: "08:10 UTC", event: "Customer reports missing scheduled work" }, { time: "08:42 UTC", event: "Cron path is corrected and overdue jobs are drained safely" }],
    notes: "Avoid triggering all overdue jobs blindly. Correct scheduling, inspect queue volume, then drain with rate and duplication safeguards.",
    choices: ["The system cron still targets the pre-migration document root", "The mail domain lacks SPF", "PHP ran out of memory", "Cloudflare cached the scheduled posts"], correctAnswer: 0,
    explanation: "WordPress pseudo-cron is intentionally disabled, and the only scheduler calls a path that disappeared during migration. The queued jobs remain executable manually.",
    investigationSummary: { rootCause: "The external cron job retained an obsolete path after hosting migration while WordPress pseudo-cron was disabled.", evidence: ["Cron stderr says the target file is missing", "Configured path differs from current document root", "Scheduled actions work when invoked manually"], impact: "Publishing and email tasks accumulated without execution.", resolution: "Correct the cron command, run a controlled test, drain overdue jobs safely, and verify the next scheduled execution." },
    prevention: "Include cron definitions in migration validation, monitor last-run timestamps, alert on overdue queues, and document whether system or loopback cron owns scheduling.",
    customerFriendlyReply: "The website migration changed the location used by its scheduler, so background tasks stopped starting automatically. We corrected that path and safely processed the delayed publishing and email jobs.",
  }),
  webIncident({
    id: "ssl-mixed-content", incidentId: "INC-0036", title: "SSL mixed content", product: "SSL", severity: "Medium", category: "SSL", difficulty: "Foundational", error: "Blocked mixed active content",
    customerMessage: "The browser shows the site as not fully secure after enabling HTTPS. Some homepage images are missing and the menu script does not run.",
    customerImpact: "Visitors see security warnings and some page assets are blocked.",
    logs: `[14:11:03] GET / 200 scheme=https\n[browser] Mixed Content: requested http://example.test/wp-content/uploads/hero.jpg\n[browser] Blocked loading active content http://example.test/wp-content/themes/site/menu.js`,
    requestDetails: `Document URL: https://example.test/\nHTML contains absolute http:// URLs in page-builder content\nCSS asset URLs are already HTTPS\nTLS certificate validates successfully`,
    observedError: `Browser console:\nMixed Content warning for image\nBlocked mixed active content for script\nNetwork panel shows no request sent for blocked script.`,
    deploymentDetails: `HTTPS redirect enabled today\nWordPress Address updated to https://\nHistorical page-builder content not rewritten`,
    environmentDetails: `Certificate valid=true\nHTTPS response=200\nHSTS not yet enabled\nCDN disabled`,
    timeline: [{ time: "13:50 UTC", event: "HTTPS cutover completes" }, { time: "14:05 UTC", event: "Customer reports missing assets" }, { time: "14:14 UTC", event: "Browser console reveals stored HTTP asset URLs" }, { time: "14:30 UTC", event: "Serialized-safe URL update and cache purge restore assets" }],
    notes: "Use a WordPress-aware search/replace for stored serialized data and verify external resources; a raw SQL replacement can corrupt content.",
    choices: ["Stored asset URLs still use HTTP on an HTTPS page", "The SSL certificate has expired", "The domain MX record is incorrect", "The origin is refusing Cloudflare connections"], correctAnswer: 0,
    explanation: "The document and certificate are secure, but HTML references HTTP resources. Browsers warn on passive content and block the active script.",
    investigationSummary: { rootCause: "Page content retained absolute HTTP URLs after the HTTPS migration.", evidence: ["Certificate and main document validate", "Console names specific HTTP assets", "Affected URLs originate in historical page-builder content"], impact: "Security indicators degraded and browser-blocked assets broke parts of the page.", resolution: "Back up the database, replace stored URLs safely, update templates, clear caches, and crawl for remaining mixed content." },
    prevention: "Use relative or HTTPS URLs, include content rewriting in HTTPS migrations, scan releases for mixed content, and enable HSTS only after validation.",
    customerFriendlyReply: "The site certificate was working, but a few saved image and script links still used the older unsecured address. We updated those links and confirmed the page now loads fully over HTTPS.",
  }),
  webIncident({
    id: "ssl-certificate-expired", incidentId: "INC-0037", title: "SSL certificate expired", product: "SSL", severity: "Critical", category: "SSL", difficulty: "Operational", error: "NET::ERR_CERT_DATE_INVALID",
    customerMessage: "Visitors receive a privacy warning before the website opens. The certificate was supposed to renew automatically, and no site files changed.",
    customerImpact: "Browsers discourage or prevent visitors from accessing the website securely.",
    logs: `[02:00:02] certbot renew: authorization failed status=403\n[02:00:02] detail=Invalid response from http://example.test/.well-known/acme-challenge/token\n[08:21:14] tls notAfter=2026-07-06T00:00:00Z`,
    requestDetails: `Certificate subject: example.test, www.example.test\nCurrent time: 2026-07-06 08:21 UTC\nExpiry: 2026-07-06 00:00 UTC\nRenewal attempts failed for 12 days`,
    observedError: `Browser: NET::ERR_CERT_DATE_INVALID\nTLS client: certificate has expired\nHTTP challenge path returns security-plugin 403.`,
    deploymentDetails: `No site deployment\nSecurity rule added 14 days ago\nACME challenge directory was not excluded`,
    environmentDetails: `Port 443 reachable=true\nCertificate hostname matches=true\nCertificate chain valid except date=true\nRenewal timer active=true`,
    timeline: [{ time: "Jun 24", event: "First renewal attempt receives challenge 403" }, { time: "Jul 06 00:00 UTC", event: "Certificate expires" }, { time: "08:10 UTC", event: "Browser warning reported" }, { time: "08:43 UTC", event: "Challenge access is restored and certificate renewed" }],
    notes: "Renewing the certificate restores service; fixing and monitoring the failed challenge prevents recurrence.",
    choices: ["The certificate expired after ACME validation was blocked", "The certificate hostname excludes www", "Cloudflare Flexible SSL caused a loop", "The DNS A record points to the old server"], correctAnswer: 0,
    explanation: "The certificate identity and chain are otherwise correct, but its validity period ended after repeated 403 responses blocked automatic renewal.",
    investigationSummary: { rootCause: "The SSL certificate expired because a security rule blocked the automated ACME renewal challenge.", evidence: ["TLS inspection shows a past expiry time", "Renewal logs show repeated challenge 403 responses", "The blocking rule predates the first failed renewal"], impact: "Browsers displayed a severe certificate warning to all HTTPS visitors.", resolution: "Allow the ACME challenge safely, renew and install the certificate, reload the web server, and verify automatic renewal." },
    prevention: "Alert on certificate age and renewal failures, test renewal regularly, and preserve ACME challenge access when changing security rules.",
    customerFriendlyReply: "The website certificate expired after its automatic renewal check was blocked by a security rule. We restored that validation path, renewed the certificate, and confirmed secure access is working normally.",
  }),
  webIncident({
    id: "email-spf-missing", incidentId: "INC-0038", title: "Email SPF record missing", product: "Email", severity: "Medium", category: "Email", difficulty: "Foundational", error: "SPF result: none",
    customerMessage: "Website emails are sending, but several recipients say they arrive in spam. The mail provider asked us to verify the domain's authentication records.",
    customerImpact: "Outgoing transactional and contact-form messages have reduced deliverability.",
    logs: `[09:31:44] smtp accepted message_id=synthetic-884\n[recipient] Authentication-Results: spf=none smtp.mailfrom=example.test\n[recipient] dkim=pass header.d=mailer.example.test dmarc=pass`,
    requestDetails: `Authoritative TXT lookup for example.test:\n"site-verification=redacted"\nNo record beginning with v=spf1\nSending provider include value documented in account settings`,
    observedError: `Message is accepted, not bounced.\nRecipient headers report SPF=none.\nSpam placement varies by receiving provider.`,
    deploymentDetails: `Website mail integration unchanged\nSending provider domain verification partially complete\nNo application exceptions`,
    environmentDetails: `SMTP authentication=true\nDKIM=pass\nDMARC=pass via aligned DKIM\nSPF=none`,
    timeline: [{ time: "Yesterday", event: "Recipients begin reporting spam placement" }, { time: "09:31 UTC", event: "Support captures sanitized authentication results" }, { time: "09:44 UTC", event: "Authoritative TXT records are reviewed" }, { time: "10:12 UTC", event: "Valid SPF policy is published and monitored" }],
    notes: "SPF improves authentication but does not guarantee inbox placement. Preserve existing authorized senders and maintain only one SPF policy record.",
    choices: ["The sending domain has no valid SPF TXT policy", "The MX record points to the wrong inbound provider", "The website certificate expired", "The SMTP server rejected the message"], correctAnswer: 0,
    explanation: "Mail is successfully accepted and DKIM passes, but recipient authentication explicitly reports SPF none and authoritative DNS has no SPF policy.",
    investigationSummary: { rootCause: "The domain lacked a valid SPF TXT record authorizing its outbound mail provider.", evidence: ["Recipient headers report SPF=none", "Authoritative TXT response has no v=spf1 record", "SMTP delivery succeeds, ruling out an application send failure"], impact: "Messages were more likely to be filtered as spam.", resolution: "Publish one validated SPF record covering approved senders, wait for DNS caches, and verify headers with controlled messages." },
    prevention: "Inventory sending services, monitor SPF/DKIM/DMARC alignment, avoid multiple SPF records, and retest authentication after DNS changes.",
    customerFriendlyReply: "The website was sending messages successfully, but the domain was missing an email authentication record used by receiving providers. We added the correct SPF policy and are monitoring delivery results.",
  }),
  webIncident({
    id: "email-mx-incorrect", incidentId: "INC-0039", title: "Email MX record incorrect", product: "Email", severity: "High", category: "Email", difficulty: "Operational", error: "Inbound mail routed to wrong provider",
    customerMessage: "Our team can send email, but messages sent to our domain bounce or never arrive. This started after the DNS zone was rebuilt during the website migration.",
    customerImpact: "Inbound business email is not reaching employee mailboxes.",
    logs: `[sender] 550 5.1.1 recipient rejected by mail.old-provider.test\n[dns] MX example.test → 10 mail.old-provider.test\n[current mail admin] expected MX → mx1.new-provider.test, mx2.new-provider.test`,
    requestDetails: `Authoritative MX records:\n10 mail.old-provider.test.\n\nActive mailbox provider supplied two different MX targets.\nWebsite A record is correct and unrelated.`,
    observedError: `External test message connects to old provider.\nOld provider has no mailbox for recipient.\nOutbound authenticated mail through new provider succeeds.`,
    deploymentDetails: `DNS zone recreated from an outdated export\nWebsite cutover successful\nMail service itself not migrated`,
    environmentDetails: `Nameservers correct=true\nMX authoritative answer incorrect=true\nNew provider mailbox active=true\nTTL=1800`,
    timeline: [{ time: "Yesterday 21:00 UTC", event: "DNS zone is imported from an old backup" }, { time: "08:02 UTC", event: "First inbound bounce is reported" }, { time: "08:24 UTC", event: "SMTP route is traced through authoritative MX" }, { time: "08:37 UTC", event: "Correct provider MX records are restored" }],
    notes: "Website and email DNS are separate services. Preserve and verify MX, SPF, DKIM, and verification records during any zone migration.",
    choices: ["The authoritative MX records point to the previous mail provider", "The domain lacks SPF for outbound messages", "Cloudflare proxy blocks SMTP", "WordPress cron stopped processing mail"], correctAnswer: 0,
    explanation: "Outbound mail works through the active provider, while external senders follow the authoritative MX target to an old system without the mailbox.",
    investigationSummary: { rootCause: "An outdated DNS zone import replaced the current MX records with the previous mail provider's target.", evidence: ["Authoritative MX names the old provider", "External SMTP connects to that provider", "Current mailbox and outbound service remain healthy"], impact: "Inbound messages bounced or were routed away from active mailboxes.", resolution: "Restore the correct MX records and priorities, verify authoritative answers, monitor queues, and ask senders to retry hard bounces." },
    prevention: "Export current DNS before migration, inventory non-web records, require peer review for zone imports, and run inbound/outbound mail tests after cutover.",
    customerFriendlyReply: "The website migration restored an older mail-routing record, so incoming messages were sent to the previous provider. We corrected the MX records and confirmed new test messages reach the active mailboxes.",
  }),
  webIncident({
    id: "malware-warning", incidentId: "INC-0040", title: "Malware warning on website", product: "Malware", severity: "Critical", category: "Malware", difficulty: "Escalation", error: "Security scanner detects injected PHP",
    customerMessage: "A browser and our security plugin warn that the site may be harmful. We also noticed unfamiliar administrator accounts and redirects on some mobile visits.",
    customerImpact: "Visitor trust and account security are at risk; some traffic is redirected away from the legitimate site.",
    logs: `[04:18:12] file_integrity modified=/wp-includes/class-wp.php checksum_mismatch\n[04:18:13] suspicious eval(base64_decode(...)) in /wp-content/uploads/2026/06/cache.php\n[04:19:02] admin_user_created username=system_backup source_ip=synthetic-redacted`,
    requestDetails: `Scanner findings:\n3 modified core files\n1 executable PHP file under uploads\n2 unknown administrator accounts\nOutdated abandoned plugin version=2.1.0`,
    observedError: `Mobile user-agent receives intermittent 302 to an unrelated domain.\nDesktop administrator may see normal cached content.\nSearch/browser reputation warning is active.`,
    deploymentDetails: `No authorized release in seven days\nFile modifications occurred outside deployment window\nLast clean offsite backup: three days ago`,
    environmentDetails: `WordPress auto-updates=partial\nAbandoned plugin enabled=true\nMFA for administrators=false\nFile editor enabled=true`,
    timeline: [{ time: "Three days ago", event: "Last known-clean backup completes" }, { time: "04:18 UTC", event: "Integrity monitor identifies unauthorized modifications" }, { time: "04:25 UTC", event: "Site is contained and credentials begin rotating" }, { time: "06:10 UTC", event: "Clean restore, patching, and validation complete" }],
    notes: "Treat this as a security incident: contain first, preserve evidence, rotate credentials from a clean device, remove persistence, and request reputation review after remediation.",
    choices: ["The site contains injected code and unauthorized modifications", "A large image causes a browser warning", "Cloudflare strict mode rejects the certificate", "The DNS TTL has not propagated"], correctAnswer: 0,
    explanation: "Checksum mismatches, executable code in uploads, unauthorized administrators, and selective redirects together indicate compromise rather than a harmless scanner false positive.",
    investigationSummary: { rootCause: "Attackers injected code and modified PHP files, likely through an outdated plugin and weak administrative access controls.", evidence: ["Core checksums do not match", "Obfuscated executable PHP appears in uploads", "Unauthorized admin creation and conditional redirects are recorded"], impact: "Visitors faced malicious redirects and the site's integrity could not be trusted.", resolution: "Contain the site, preserve evidence, restore or rebuild from clean sources, remove persistence, patch software, rotate all credentials, and request reputation review." },
    prevention: "Remove abandoned software, enforce MFA and least privilege, disable unnecessary file editing, monitor integrity, maintain tested offsite backups, and patch promptly.",
    customerFriendlyReply: "We confirmed unauthorized code changes on the website and immediately contained access. We restored clean files, removed the vulnerable component, rotated credentials, and added monitoring while reputation services re-evaluate the site.",
  }),
  webIncident({
    id: "website-performance-hero-image", incidentId: "INC-0041", title: "Website performance regression", product: "Performance", severity: "Medium", category: "Performance", difficulty: "Operational", error: "Largest Contentful Paint regression",
    customerMessage: "The homepage became noticeably slower after the new campaign launched. Server response time looks normal, but the main banner takes several seconds to appear on mobile.",
    customerImpact: "Mobile visitors wait longer for meaningful content and campaign conversion may be affected.",
    logs: `[11:00:12] server_ttfb=214ms\n[11:00:18] browser LCP=6.4s element=img.hero-campaign\n[11:00:18] resource hero-final.png transfer=6.8MB dimensions=5200x2900`,
    requestDetails: `Homepage waterfall:\nHTML 42 KB / 214 ms\nCSS 71 KB / 180 ms\nHero PNG 6.8 MB / 5.9 s\nNo responsive srcset; loading=eager`,
    observedError: `Lighthouse mobile:\nLCP 6.4 s (poor)\nTTFB 0.2 s (healthy)\nImage displayed at 1280x714 but source is 5200x2900.`,
    deploymentDetails: `Campaign content published 10:42 UTC\nNo application or hosting release\nPrevious hero WebP size: 286 KB`,
    environmentDetails: `CDN cache=hit\nOrigin CPU=18%\nCompression for PNG not material\nMobile test bandwidth=simulated 4G`,
    timeline: [{ time: "10:42 UTC", event: "New campaign hero is published" }, { time: "10:51 UTC", event: "Real-user LCP alert rises" }, { time: "11:00 UTC", event: "Waterfall isolates a 6.8 MB LCP image" }, { time: "11:24 UTC", event: "Responsive optimized formats reduce LCP" }],
    notes: "A CDN hit does not make an oversized asset cheap. Compare transfer size, display dimensions, and the actual LCP element.",
    choices: ["The new hero image is oversized and lacks responsive optimization", "The origin database is slow", "DNS propagation is incomplete", "PHP memory is exhausted"], correctAnswer: 0,
    explanation: "Server timing remains normal and the regression begins with campaign publishing. The browser spends nearly the entire LCP interval downloading an oversized image.",
    investigationSummary: { rootCause: "A 6.8 MB hero image without responsive variants became the page's Largest Contentful Paint resource.", evidence: ["TTFB and origin health remain normal", "LCP element is the new hero", "Transfer size and timing dominate the waterfall"], impact: "Homepage LCP regressed, especially on mobile connections.", resolution: "Resize and encode the hero in modern formats, provide responsive sources and dimensions, preload only the correct critical variant, and purge the CDN." },
    prevention: "Set media size budgets, automate image derivatives, monitor real-user Core Web Vitals, and review campaign assets before publishing.",
    customerFriendlyReply: "The new campaign image was much larger than the size displayed on the page, which slowed its appearance on mobile connections. We optimized it for responsive delivery and confirmed the homepage loads substantially faster.",
  }),
  webIncident({
    id: "wordpress-migration-old-site", incidentId: "INC-0042", title: "WordPress migration shows old site", product: "WordPress", severity: "High", category: "WordPress", difficulty: "Escalation", error: "Old release served after migration",
    customerMessage: "The migration team sees the new site, but our office and some customers still see the old homepage. Updates made in the new wp-admin do not appear for everyone.",
    customerImpact: "Visitors receive inconsistent content and editors cannot trust which production site is active.",
    logs: `[17:02:10] new-origin release_marker=migration-2026 access from mobile network\n[17:02:18] old-origin release_marker=legacy-2025 access from office public IP\n[17:03:01] CDN cache key host=example.test age=7210`,
    requestDetails: `Authoritative A example.test → 198.51.100.27 (new)\nOffice workstation hosts file: 192.0.2.41 example.test\nCDN cache contains old homepage from before cutover\nDirect new origin returns current content`,
    observedError: `Same URL returns different release markers by network.\nOffice resolves through hosts override to old IP.\nOther affected requests receive a cached old HTML response.`,
    deploymentDetails: `WordPress files and database migrated successfully\nNew origin validated before cutover\nOld origin retained for rollback`,
    environmentDetails: `Authoritative DNS correct=true\nOffice hosts override stale=true\nCDN purge after cutover=false\nApplication caches separated by origin`,
    timeline: [{ time: "15:00 UTC", event: "Migration and new-origin validation complete" }, { time: "16:00 UTC", event: "Authoritative DNS changes to new origin" }, { time: "17:02 UTC", event: "Release markers reveal two delivery paths" }, { time: "17:20 UTC", event: "Hosts override and CDN cache are cleared" }],
    notes: "Use a visible release marker and compare DNS, local overrides, CDN age, and origin logs. Do not repeat the migration when the new origin is already correct.",
    choices: ["A stale hosts-file override and CDN cache still serve the old origin/content", "The new WordPress database import failed", "The origin certificate expired", "The active theme has a PHP fatal error"], correctAnswer: 0,
    explanation: "Authoritative DNS and the new origin are correct. The office bypasses DNS through a stale hosts entry, while other inconsistent responses expose old CDN cache age.",
    investigationSummary: { rootCause: "Stale local hosts-file routing and an unpurged CDN cache continued serving the old site after a successful migration.", evidence: ["New origin returns the expected release marker", "Office hosts file explicitly maps the old IP", "Affected CDN response predates the cutover"], impact: "Editors and visitors saw inconsistent site versions.", resolution: "Remove temporary hosts overrides, purge old CDN HTML, verify representative networks, and monitor old-origin traffic before retirement." },
    prevention: "Track temporary hosts entries, include CDN purge in cutover, add release markers, validate from multiple networks, and retain a documented rollback window.",
    customerFriendlyReply: "The migration itself was successful, but two older delivery paths were still showing the previous site. We removed the temporary local routing and cleared the cached homepage, then verified the current version from multiple networks.",
  }),
];
